### ISSUE TITLE
NTT and e10s

### ISSUE THREAD

**Issue by hurda** [darktrojan/newtabtools#100]
Mozilla is converting their newTab.xul to HTML due to issues with e10s.
`newTab.xul cannot be rendered properly in the content process. We should be using HTML there.`
https://bugzilla.mozilla.org/show_bug.cgi?id=1167601

Will NTT run into the same problems?

**Comment by darktrojan** [comment]
[This related bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1021667) is going to be a huge pain in the backside. I think I'll have some time to handle it though because it'll cause problems for Mozilla too.

**Comment by darktrojan** [comment]
I've made some progress, and put it on the `e10s` branch. I haven't begun to run things in a remote browser to see what's broken.
