### ISSUE TITLE
Will NTT be signed?

### ISSUE THREAD

**Issue by paulri** [darktrojan/newtabtools#101]
8 of the 11 extensions I use are already signed. NTT gets continuous updates (thanks for all your work)---it looks and works great. I'm wondering, since this is obviously not abandonware, are you planning on getting this signed in the near future? Or do plan on not getting this done? Just wondering.....

**Comment by darktrojan** [comment]
It does get signed but it doesn't get the `-signed`

**Comment by paulri** [comment]
OK, thanks. I was worried that I'd have to start looking for a replacement if you decided to not get them signed.  I wasn't too confident I could find an addon as good as yours. :)
