### ISSUE TITLE
Thumbnail visual bug

### ISSUE THREAD

**Issue by CreeperLava** [darktrojan/newtabtools#105]
Thumbnail refreshs are bugged for certain sites. One image will explain it better than words :
![1](https://cloud.githubusercontent.com/assets/12874678/8145202/cfc6eff0-11fe-11e5-9b52-7025a93b1c47.png)
I only included two thumbnails for privacy purposes, but all twenty thumbnails but one have this weird black stripe at the bottom, like the page wasn't fully loaded when the thumbnail was created. I have an add-on that could be the cause of it : NoSquint, which allows me to change the default zoom for all websites.
Keep up the good work and have a good day !

**Comment by darktrojan** [comment]
NoSquint could be causing this, although it seems odd. I use Firefox's built in thumbnail code, so thumbnail bugs should be reported to them.

It looks like at some point the width was calculated wrong and made twice what it should be. Have you got two monitors, by any chance?

**Comment by CreeperLava** [comment]
I have two monitors indeed, and have configured my desktop as 3840*1080 through NVIDIA Surround.
