### ISSUE TITLE
Allow us to move the "Edit, Pin, & Remove this tile" options in context menu?

### ISSUE THREAD

**Issue by paulri** [darktrojan/newtabtools#110]
Just saw the update for New Tab Tools that gives us those 3 options in the context menu. That is very handy. Because I am so used to using the context menu & seeing the open link in new tab feature at the top, I am wondering if there will be a way to move those three options down in the context menu (below the "open link in new tab" option). That would be very helpful.

**Comment by 01i** [comment]
I agree that it would be great to move these options down a bit, I habitually right-click a tile and then click to open in a new tab. I now keep clicking edit tile instead of new tab, because it's the option at the top of the list (where open in new tab used to be).

**Comment by darktrojan** [comment]
I can certainly see your point of view, because that's the sort of thing I do too. The next best place to put them, in my opinion, is here:

![](https://i.imgur.com/j15TXO8.png)

That's probably what I'll end up doing.

**Comment by paulri** [comment]
That would be fine. It wasnt the ability to move those options per se that was important, just that it wouldnt break up what in all other cases is a reflex, muscle memory action of selecting the first or second option to open in a new tab. Your option (to simply move them down) would be just fine.

**Comment by paulri** [comment]
Just got update 50. I see the change. 

Thanks a lot.
