### ISSUE TITLE
Changing background images

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/newtabtools#112]
I've been asked a few times about having the background image cycle through a group of images, like many OS desktops do. There are a few issues to work through, such as when to change the image, and how to decide if the light or dark theme is best for any particular image. But I have started.

**Comment by CristianCantoro** [comment]
May I also suggest the possibility to use an RSS feed as source, here's a great example: [NASA Image of the Day](https://www.nasa.gov/rss/dyn/lg_image_of_the_day.rss). Such feeds usually provide high-res images.
One possible (additional) issue is that some images are darker in colour (and thus are best viewed using the dark theme), while other may be light in colour (and thus best viewed with the light theme).

**Comment by darktrojan** [comment]
Okay, so there's some progress on the `backgroundimage` branch that is useable. YMMV. It could break, fail, or explode at any time. You'll need to set the prefs `extensions.newtabtools.background.directory` to a directory to use, and `extensions.newtabtools.background.mode` to 0, 1 or 2. 0 is the old behaviour; 1 is one random image per session; 2 is a random image for each new tab.

**Comment by darktrojan** [comment]
`backgroundimage` has been merged to `unreleased`. It will be released with the next version, but doesn't do anything without changing the prefs listed above. In addition, setting the pref `extensions.newtabtools.background.changeinterval` to a positive integer will cause the background image to change every [value of pref] minutes.

Although the code to make this work is being released, it's not extensively tested or polished, so use it at your own risk.

**Comment by darktrojan** [comment]
I've just made some UI for this. I haven't finished it yet but it exists. Still on the `backgroundimage` branch.
