### ISSUE TITLE
Request:  Tile for spawnign tab

### ISSUE THREAD

**Issue by siblify** [darktrojan/newtabtools#120]
Sorry - this isn't an issue as such but I was wondering if it would be easy in a future release to include the option of a tile with the URL of the tab that spawned the new tab eg. if you were on google.com and opened a new tab the first tile would be for google.com?  I would find it really handy as I am often wanting to start a new task using the same webpage concurrent to the task I am working on.

**Comment by darktrojan** [comment]
Press `Ctrl` (or `Cmd`, I think, for Mac) and click on the refresh button, instead of the new tab button. Bingo, duplicate of the current tab.

**Comment by siblify** [comment]
I never knew that - great tip thanks!
