### ISSUE TITLE
Tile flickers when clicked on

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/newtabtools#121]
This happens especially with my Facebook tile, but I guess it happens with others too. Don't know why.

**Comment by darktrojan** [comment]
Really? I'm the only one who sees this?

**Comment by hellexecutor** [comment]
This happens to me too. When I click some tile and then move mouse to another tile - they both begin to flicker.

**Comment by darktrojan** [comment]
@hellexecutor Are you a Linux user by any chance?

**Comment by hellexecutor** [comment]
Nope. Flickering acurs both on Windows 8 at home & Windows 7 at work (latest stable Firefox x86 & Newtabtools in both cases).

**Comment by mechacrab** [comment]
Happens here as of recently.  On Linux!  Yay.

Running openSUSE Tumbleweed/Plasma 5.5/FF 43.0.3/Breeze-Dark for GTK2/3 themes.  

Flickers, seems to have some weird, intermittent sizing error when it does it.  Have tried removing "Recently Closed Tabs" and just generally messing with settings; haven't tried an uninstall/reinstall yet.

Cannot reproduce the problem reliably - specific tiles or behaviors don't seem to be the case.

Hope this helps a *little*.

**Comment by darktrojan** [comment]
I made a change today (not released) which I hope might fix this. No problems so far.

**Comment by mechacrab** [comment]
Will make sure to report back after the next update if the problem persists here. :)

**Comment by darktrojan** [comment]
Spoke too soon. :-(

**Comment by mechacrab** [comment]
You're not going to like this answer.  Well, maybe you will.  

And it's potentially "spoke too soon" but seems to have fixed it.

Open New Tab Page.  Control+Scroll on it to adjust zoom level - up, down, whatever.

Problem is gone here.

If it works for you, well, I'm not responsible for any torn out hair, drinking problems, or sheep-kicking. :)
