### ISSUE TITLE
Pin icon background-position is wrong

### ISSUE THREAD

**Issue by rybak** [darktrojan/newtabtools#126]
![pinned-tile](https://cloud.githubusercontent.com/assets/624072/10073068/0868a77e-62cf-11e5-9378-99c644b594cd.png)

Should be similar to this:
![pinned-tile2](https://cloud.githubusercontent.com/assets/624072/10073099/43a183f6-62cf-11e5-80b1-6b5ae6501231.png)

I'm using Firefox version 40.0.3 on Windows 7.
Newtabtools version 51.

**Comment by darktrojan** [comment]
It looks okay on my copy. It looks like the icons in your image are not the [ones from NTT](https://github.com/darktrojan/newtabtools/blob/master/content/controls.png), so I'm wondering if you have an extension that is changing the CSS?

**Comment by rybak** [comment]
You are correct, Classic Theme Restore's "Alternative New tab appearance" was turned on. Thanks.
