### ISSUE TITLE
Cleared history/cookies & every URL I hit is getting a new tile

### ISSUE THREAD

**Issue by ivyclarice** [darktrojan/newtabtools#127]
Thanks so much for the wonderful add on! It's been a lifesaver and I'm extremely fond of it. However, I've encountered a quirk that I hadn't experienced before. 

Yesterday, I cleared my entire Firefox history, cookies, etc., and now every time I visit a URL, a new tile is appearing for the URL. For instance, I went browsing on Amazon for carob food products and every single product I looked at had its own new tile. The same when I tried to browse Sims 4 downloads. As you can imagine, the page fills up quickly and it's time-consuming to manually delete them one by one.

This may very well be ignorance or end-user error, but I couldn't find any options for shift-clicking to delete more than one tile at a time, or to control the parameters that prompt it to create a new tile. Prior to the great history & cookie clearing, this wasn't happening.

**Comment by darktrojan** [comment]
That's expected. The tiles are filled from your history if you haven't added any pinned tiles. If there's not much in your history, that's what you'll get.

**Comment by ivyclarice** [comment]
Got it, thank you! Wasn't sure if end-user problem (though I figured it
was) or something buggy. Great extension, thank you so much.
