### ISSUE TITLE
Shows horizontally scrollbar

### ISSUE THREAD

**Issue by rugk** [darktrojan/newtabtools#129]
![scrollbar](https://cloud.githubusercontent.com/assets/11966684/10118562/65db8446-647b-11e5-876f-c7d46f89d02a.PNG)

This are my settings (sorry for the German language):
![scrollbar_settings](https://cloud.githubusercontent.com/assets/11966684/10118563/768f5178-647b-11e5-85ae-4314a2c9ef11.PNG)

Firefox 41.0

**Comment by darktrojan** [comment]
Hmm, that's unusual. Are you running any other extension that might be modifying the new tab page, such as Classic Theme Restorer or Stylish?

**Comment by rugk** [comment]
> Classic Theme Restorer or Stylish?

No.  Only Greasemonkey, NoScript, Adblock Plus and some others...

**Comment by seiterseiter** [comment]
Im having the exact same issue

**Comment by rugk** [comment]
Also note that the scrollbar is hidden when you click on the settings wheel. If you close the settings "popup" the scrollbar is shown again.

**Comment by seiterseiter** [comment]
its apparently caused by this:
#options-toggle {
  -moz-margin-end: -1px;
}

and this should fix it:
@-moz-document url(about:newtab) {
  #options-toggle {
    -moz-margin-end: 0px;
  }
}

**Comment by darktrojan** [comment]
So it is. I must've missed that when I first changed things.

**Comment by seiterseiter** [comment]
Hopefully you release a bugfix soon, glad i could help :)
