### ISSUE TITLE
Checkbox text is not aligned if was changed

### ISSUE THREAD

**Issue by yfdyh000** [darktrojan/newtabtools#132]
![2015-10-02 19 36 50](https://cloud.githubusercontent.com/assets/1769875/10245763/45624a12-693d-11e5-9859-998a9d3a0e88.png)

I'm not sure it's reason, maybe it is a XUL's bug.

**Comment by darktrojan** [comment]
On Windows, XUL checkboxes and radios have padding. I don't know why. Anyway it's gone now.

**Comment by yfdyh000** [comment]
099cb0f2fe8f0077cb36e86aa3d58839df9319a4 seems not wroks for me. Fx42.0b3 on Win8.1.

**Comment by darktrojan** [comment]
Maybe I misunderstood what you wanted. Could you explain again?

**Comment by yfdyh000** [comment]
The padding disappeared if checkboxes once changes.
![2015-10-07 21 03 49](https://cloud.githubusercontent.com/assets/1769875/10338312/fc77139c-6d37-11e5-89a8-2c1b9afb82dd.png)

**Comment by yfdyh000** [comment]
![2015-10-08 01 01 25](https://cloud.githubusercontent.com/assets/1769875/10345076/94f7f87c-6d59-11e5-901c-f613c4aba1c6.png)
![2015-10-08 01 01 39](https://cloud.githubusercontent.com/assets/1769875/10345077/94fc5534-6d59-11e5-8fa9-48c7dbeed074.png)

**Comment by darktrojan** [comment]
Okay, I see it now! And it's cause by something odd happening in XUL, but luckily I can override it.

By the way, these aren't called checkboxes. They're called (depending on who you talk to) drop down boxes, list boxes, or XUL calls them menu lists. Checkboxes are the small square further down the page that you can click to turn things on or off. The mark in the box is called a checkmark (by the Americans) or a tick (by everyone else). That's what confused me!

**Comment by yfdyh000** [comment]
You're right, I made a mistake it's name.

**Comment by yfdyh000** [comment]
Everything looks good. Thank you.
