### ISSUE TITLE
NewTabTools broken on latest Firefox nightly

### ISSUE THREAD

**Issue by hooloovoo79** [darktrojan/newtabtools#136]
NewTabTools no longer works with the latest nightly (and likely will not work with any subsequent ones) because of changes to let, var, and const.

You can read about this here:
https://hacks.mozilla.org/2015/07/es6-in-depth-let-and-const/
https://groups.google.com/forum/#!topic/mozilla.dev.platform/XoW35OxqDYI

These two errors were in the console. Hopefully they will act as a starting point to fix:

TypeError: redeclaration of let Cu
<anonymous> fx-newTab.js:7
fx-newTab.js:7:1

ReferenceError: gTransformation is not defined
window_load() newTab.js:607
newTab.js:607:5

**Comment by darktrojan** [comment]
I have *just* landed a patch to fix that!

**Comment by hooloovoo79** [comment]
Great! Guess I didn't need to harass you then. Keep up the good work!

**Comment by darktrojan** [comment]
No problem, it's nice to know somebody notices when I break things. I'll leave this open until a new release happens.
