### ISSUE TITLE
New Tab Tools as home page

### ISSUE THREAD

**Issue by Dangthrimble** [darktrojan/newtabtools#141]
Any chance an option could be added to allow New Tab Tools to be the home page? I don't have a home page and have always felt it would be good if the New Tab could be my home page.

**Comment by darktrojan** [comment]
Just set your homepage to `about:newtab`.

**Comment by Dangthrimble** [comment]
If only I'd known that months ago! But now I do, and it's even better with New Tab Tools.

Thanks

=O)
