### ISSUE TITLE
Request:  Opacity Slider for Tiles

### ISSUE THREAD

**Issue by AzDayton** [darktrojan/newtabtools#142]
Hi!  Great project.  It's a pleasure to support and promote it!

If you're looking for possible improvement suggestions, I thought that an opacity slider for the tiles would be a neat feature.  That way we could make the tiles reveal more of the background art, or show the tile more clearly, according to user preference.

Thanks and keep up the great work!

**Comment by darktrojan** [comment]
Not a bad idea! I'll look into it.

**Comment by darktrojan** [comment]
This feature will be in the next version, which is currently stuck in the review queue. Enjoy.
