### ISSUE TITLE
Info/status bar

### ISSUE THREAD

**Issue by hondacbr600** [darktrojan/newtabtools#143]
Hi there,
every single time i start ff, get this:
![capture](https://cloud.githubusercontent.com/assets/15723130/11025599/c4b60fd0-86a5-11e5-8649-42c0e4a94089.PNG)
which can be really annoying, because shrink visible area.
How to allow permanently New tab tools to change my new tab page?

**Comment by darktrojan** [comment]
That message only shows if another add-on (or some malware) is trying to change your new tab page. (New Tab Tools uses the default page, so though the button says "change" it actually means "reset to default".)

[This page](https://support.mozilla.org/en-US/kb/remove-toolbar-has-taken-over-your-firefox-search) might also be helpful.

**Comment by hondacbr600** [comment]
It was classic theme restorer. Disabled its new tab page modifications and everything is ok now.
Thanks,
Peter
