### ISSUE TITLE
Dragging Tiles

### ISSUE THREAD

**Issue by MutantOctopus** [darktrojan/newtabtools#148]
Hey, I really like NTT, but there's just one issue I have-- there's no way to actually move a tile around. The best I can do is deleting and recreating and pinning tiles until they slide into the right place. Am I doing it wrong, or is it a bug?

**Comment by Halothreefan** [comment]
I can't do it either. Using version 56.

**Comment by darktrojan** [comment]
Uhh, I've broken it! Sorry about that.
