### ISSUE TITLE
New thumbnails code in Firefox 44

### ISSUE THREAD

**Issue by jagmoreira** [darktrojan/newtabtools#151]
Using NewTabTools 56.1.1 on Firefox 44.0a2 on Windows 7.
For a while now (a month or so) my thumbnails all look blurry. Like this:
![untitled](https://cloud.githubusercontent.com/assets/13685125/11611205/1eeeb592-9b87-11e5-8c9c-d864f2f472dd.png)
I have a 23'' monitor on 1080p resolution. I have no other extensions that affect the theme.
I recently did a reset of my firefox settings but I the problem remained after I reinstalled NewTabTools.

**Comment by darktrojan** [comment]
I'm pretty sure what's caused that is a change in Firefox that caused it to make smaller thumbnails. I haven't yet figured out how/if NTT will respond to the change, but you can visit about:config?filter=toolkit.pagethumbs and try different settings.

**Comment by jagmoreira** [comment]
That did it! For now anyways...

I slowly increase the minHeight and minWidth settings, cleaning the cache and re-generating the thumbnails (by removing the image and opening the page again) every time until I got a crisp image:

![untitled](https://cloud.githubusercontent.com/assets/13685125/11644568/bcd447cc-9d12-11e5-9af3-079146d75392.png)


**Initial values**
toolkit.pageThumbs.minHeight;190
toolkit.pageThumbs.minWidth;280

**Final values**
toolkit.pageThumbs.minHeight;370
toolkit.pageThumbs.minWidth;460

The `screenSizeDivisor` settings didn't affect the outcome.

Another thing I noticed was that if I did a `Refresh Thumbnail`, instead of `Remove` and opening the page again, the thumbnail gets clearer for a much lower pair of settings...

**Comment by jagmoreira** [comment]
I realized recently that this bug did not occur anymore: I reverted my hacked settings and add no more blurring.

Looking at the [changelog](https://addons.mozilla.org/en-US/firefox/addon/new-tab-tools/versions/) this was probably fixed on version 58.

So, feel free to close the ticket.
