### ISSUE TITLE
"New Tab Tools" needs to modify your page "NewTab"

### ISSUE THREAD

**Issue by Charles-770** [darktrojan/newtabtools#156]
Every time I launch Firefox I have a bottom tab telling me: "New Tab Tools" needs to modify your page "NewTab".
It's doesn't help if I click on the button 'Modify' or 'Close', it is coming back!
Is there a way to get rid of this?
Thx

**Comment by darktrojan** [comment]
You have another add-on changing your new tab page every time Firefox starts. Find it and stop it, and this message should go away. The last person who had this issue had Classic Theme Restorer installed, so try that if you have it.

**Comment by Charles-770** [comment]
Thanks.
I've found the culprit: it is "Tab Mix Plus", but it is to useful for me, I can't uninstall it :((
I will play with the settings to see if I can block only this conflict & keep it running.
