### ISSUE TITLE
"Click here to begin customizing..."

### ISSUE THREAD

**Issue by webCoordinator** [darktrojan/newtabtools#157]
I just installed this add-on in Firefox 43.0.4 and aside from no visible thumbnails or whitespace at the top of the screen, I get this green arrow that points at nothing (in the top right corner) and never goes away (with multiple browser re-starts). I presume that it's meant to lead to the customization screen somehow and only show up the first time that new tab screen is loaded.

**Comment by darktrojan** [comment]
Hmm, that's strange.
Have you done any customisation of your new tab page before? Perhaps using the Stylish add-on?

**Comment by webCoordinator** [comment]
Ah yes, Stylish. Sorry for that!
