### ISSUE TITLE
New Tab is blank

### ISSUE THREAD

**Issue by robsen100** [darktrojan/newtabtools#158]
Hi,

my new tab shows up the nine little corners on top right corner but I can't click them. 

Any suggestions? Thank you for your help.

**Comment by darktrojan** [comment]
It's broken at the moment, sorry! You can do the same thing by visiting `about:config` and setting `browser.newtabpage.enabled` to true.

**Comment by robsen100** [comment]
Ah, it helps :)
Thank you!
