### ISSUE TITLE
Incompatible with latest Firefox version

### ISSUE THREAD

**Issue by IDKwhattoputhere** [darktrojan/newtabtools#159]
> Works with Firefox 42.0 - 45.0a1

This doesn't include the latest ESR version of Firefox.
It causes Mozilla to deliver old versions to ESR users.
I personally use ESR because I'm not interested in Mozilla's experiments or in downloading a huge update every 6 weeks. Others feel the same or are limited by organisations who can't update Firefox as frequently.

**Comment by version365** [comment]
>This doesn't include the latest ESR version of Firefox.

beacuse, the latest ESR version of Firefox (v.45 stable not v.45 alpha or beta releases) isn't released yet..

**Comment by IDKwhattoputhere** [comment]
I guess you're right. It's not that long until it will be released either so I'm going to close this.
