### ISSUE TITLE
Issues with FireFox ver 43.0.4 - Add/Move/Delete Tiles Hangs FF. Help!

### ISSUE THREAD

**Issue by EStrong513** [darktrojan/newtabtools#160]
Greetings!

Love Tab Tools, it works! However, since the last few updates of Firefox, trying to add, delete or just move my tiles on the homepage is extremely slow and/or crashes Firefox. I heard some code was recently changed within Firefox that may be causing this issue. Is this something you can look into and hopefully fix soon? FYI, I'm not a coder or programmer, I'm a Cisco CLI dork, LOL.

Tab Tools is my "GO TO" and I love it. As most on here, I appreciated the work you've put into it. When you have a chance please fix my baby, LOL.

TIA, E...

**Comment by darktrojan** [comment]
Hello! I'm sorry, I don't have any idea what could be causing something like this. It sounds serious though! [Here's a few things you could try.](https://support.mozilla.org/en-US/products/firefox/fix-problems/procedures-diagnose-and-fix-problems)

**Comment by EStrong513** [comment]
Thanks for the reply!

I tried a few "Heinz 57" fixes and no luck. I disabled Tab Tools and did some editing within the FF Config to tweak FF's version of the home tab page, I was able to fiddle with it enough to get my tiles back the way I wanted and then re-enabled Tab Tools which then spaced them out perfectly. I did notice while arranging tiles while Tab Tools was disabled I had a few of the same hanging issues as before. Something is definitely going on within FF's code since the last update causing issues with tabs and tiles regardless if any add-ons are enabled or not. So for now looks like I've found the workaround until FF is updated again and maybe fixes the bug if they even identify it for the next update.

Thanks again for your reply! Always appreciate people taking the time to look into a problem and reply to the OP. If I run into any helpful info that can be of use to you or the other Tab Tools junkies, I'll post here.

Be Well, E...

**Comment by Micha-Btz** [comment]
@EStrong513 which system do you have? at work with version 43.0.4 with windows 7 there is no problem. on my linux machine at home the browser is terrible slow at all.

**Comment by EStrong513** [comment]
Hi Micha!

Win 7 Pro 64-bit. I noticed the issue once I upgraded FF to 43.0.4. Looks like a FF issue and not Tab Tools issue. When I disable TT and use tiles on FF's home page, some of the same issues happen there also. If I have time I might drop back a few versions of FF to see if the issue follows along or not. As I mentioned I have a workaround for now and other than moving tiles or adding new ones, Tab Tools is working fine for me.

Thanks for your reply, E...

PS, to add for all those on Github, I really appreciate the community and the help everyone shares here. Lot's of quality people!

**Comment by AbsoluteForce** [comment]
Hi all.
My pc have this problem,and check older versions.

My PC
- OS:Windows 7 ULT 64bit,Localized to Japanese
- Firefox:46.0a2 (2016-02-07),Localized to Japanese

Checking New Tab Tools version
- ver 56.1.1-signed : No Problem
- ver 57-59 : Hang Up doing add/move/delete tiles

**Comment by darktrojan** [comment]
That's interesting. There were some changes in v57 that could be related, but I think there would have to be a bug somewhere in Firefox, especially to cause a crash. I should've asked at the time @EStrong513, have you got any crash reports? (Go to about:crashes for a list of reports, the easiest way to find a related crash would be to cause a new one, then it would be top of the list.)

**Comment by version365** [comment]
new Tab Tools v57 causes problems for me too on both FF 43.0.4 and 44.01.. but not crashing.. In my case sometimes it lags and sometimes hangs up for 2 seconds, then goes back to normal..

Same thing is happening with Nightly latest edition too.. In Nightly, after Add/Move/Delete for some times it even gives warning "New Tab Tools may be causing Nightly to perform slowly"

**Comment by Halothreefan** [comment]
I got the same "lag" when deleting or moving tabs both on Linux Mint 17.3 64bit and Windows 10 64 bit.
I got version 59 but don't know which FF version probably the latest one.

**Comment by darktrojan** [comment]
I think I've found the cause and I may be able to avoid it. Stay tuned.

**Comment by Micha-Btz** [comment]
now it is really great on both win and linux. thanks a lot.
