### ISSUE TITLE
New Tab Tool 58 won't start

### ISSUE THREAD

**Issue by sjhboo** [darktrojan/newtabtools#163]
When I open Firefox, (I have FF version 43.0.1 installed) at the bottom of screen it reads "New Tab Tools needs to change your new tab page." I then have to click "Change" for the New Tab Tools to start working. How do I make New Tab Tools to start with FF? Is there something I need to change in the FF about:config so it starts when I open FF? It use to work, but I don't know with what FF version it started not to.

**Comment by darktrojan** [comment]
Sorry this took so long. See #156 and/or #143.
