### ISSUE TITLE
Suggestion: Confirmation dialogue for unpinning tiles

### ISSUE THREAD

**Issue by Jorlem** [darktrojan/newtabtools#164]
I would like to suggest that a confirmation dialogue box be added for when the "pin" button is clicked, unpinning the tile.  The vast majority of the time when I click that button, it is by accident, and then I need to manually re-add the tile, as it vanishes as soon as it is unpinned.  Please, either add a confirmation to make sure that the unpinning is intentional, or make it so that unpinning a tile does not instantly remove it.  There's an option specifically for removing a tile in the context menu, after all, no need to have a button that can easily do the same thing unintentionally as well.

**Comment by pnlawrence** [comment]
Ditto on the confirmation. That's what made me come here today.
