### ISSUE TITLE
background images

### ISSUE THREAD

**Issue by liamsmiths** [darktrojan/newtabtools#166]
For about the last month the "View Background Image" option in the drop down menu has been greyed out as inoperable?  Did something change to effect this option?

**Comment by arttronics** [comment]
It looks like Firefox changed the code recently. I am using a Stylish Script I created for use with that Firefox Extension to address this issue.

`@namespace url(http://www.w3.org/1999/xhtml);

/* customizedMOD - Created for both Standard and devBox releases. */
@-moz-document url("about:newtab") {

/* The above namespace and document were auto-created by Stylish when 'Write new style' was choosen from the button. */

    /* This selector will target only the body section that contains the NewTabTools desired background image. */
    body > .newtab-background {

      /* The viewport will have an inside semi-transparent black inside border.*/
      box-shadow: inset 0 0 150px 25px rgba(0,0,0,1);

    }

    /* This selector is choosen via Browser Toolbox. */
    #newtab-scrollbox > #newtab-vertical-margin, body {
        /* Because NewTabTools AddOn over-rides the entire about:newtabs page, the exisiting background-color is removed via parent background attribute. */
        background: none !important;
    }
}`

The above code is working for both stable Firefox 44.0.2 and Developers Edition 46.0a2 and is a temporary workaround until the author releases the next update with this fix.

Just in case, you can use Animated GIFs for the background images too, and on that note, use Google Image Search and choose the drop down item for 'Type' and choose 'Animated' to see lots of them. Do a image search for 'abstract' to see lots of great looking backdrops. Next image search is Matrix Rain.

Cheers

**Comment by darktrojan** [comment]
@liamsmiths Yes, something did change. The background is now on a separate layer behind everything else, so it's not possible to right click on the background now. That happened as a part of #112, which I'm considering removing anyway.
