### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by coriumalpha** [darktrojan/newtabtools#169]
Hi!
I want to help you translating this addon to spanish, can you tell me how to perform it?

**Comment by darktrojan** [comment]
The easiest way is to visit [this page](https://zoo2translate.herokuapp.com/darktrojan/newtabtools), sign in with your GitHub account, then choose Spanish from the "Create a new translation" form at the bottom.

There's already a translation called "Spanish (Spain)" which somebody has started and (I think) abandoned. You can probably copy most of what's been done there.

**Comment by coriumalpha** [comment]
Thank you @darktrojan for the info, strings are translated to Spanish (I'm not able to use "Spanish (Spain)" because as you said, it is already in use by another user. Pull request is created (Commit: 275c811990ce99132c9febcd54442da465c224ed)

:)

**Comment by darktrojan** [comment]
Wow, I really like your video. I might even add it to the NTT page, if you don't mind :-)

I'll ship your changes with the next release.

**Comment by coriumalpha** [comment]
Place the video wherever you want, I'll be pleased :)

By the way, I still have the _template_ that I used to customize the tile images, what about making a little homogeneus image library for the most common websites displayed on NTT? For the moment I have enought time for that and I think it will be interesting, maybe "Select predesigned image" from a <select></select> menu. Tell me what do you think about :)
