### ISSUE TITLE
[OFFTOPIC] Please update Element Properties for Firefox 45

### ISSUE THREAD

**Issue by birdie-github** [darktrojan/newtabtools#176]
I couldn't find this add-on among your repos, so I've got no choice but to mention this issue here.

My apologies for misusing bug tracker.

Thank you!

**Comment by darktrojan** [comment]
It is totally incompatible with multi-process Firefox, and fixing it would be a major rewrite, so I have no intention of doing so unless someone's going to pay my bills for 2 weeks while I do it.

**Comment by birdie-github** [comment]
This is sad. I thought E10S is still months away and it didn't require too much effort for smaller (simpler) add-ons. Guess I was wrong.
