### ISSUE TITLE
Missing tiles

### ISSUE THREAD

**Issue by MichaelIsGreat** [darktrojan/newtabtools#188]
This bug of missing tiles appears in version 64 I believe.

I have 10 rows and 8 columns of tiles and I have pinned so far 69 pinned tiles that occupy only 9 rows. BUT the bug is that it does NOT show 10 rows, it only shows 9 rows and the displayed tiles are only the ones that I have pinned!
Therefore, the free spaces for other tiles that are not pinned, these free spaces have completely disappeared and are not showing empty tiles!
I believe that previously these free spaces for other tiles were filled with sites that I had opened and then closed but not pinned on this addon.
Conclusion: I should see 10 rows with spaces for tiles even when I have not pinned any extra tiles apart from the 69 pinned tiles that I have.

The strange thing is that the recently closed tiles appear now at the top when you select this particular option.
Having said that, it does not mean that I still should not see free spaces for other tiles that I have not pinned yet in rows 9 and 10.

Kudos to the developer for having solved the big issue that was present with moving tiles easily and quickly when you have a big number of tiles like I have.

**Comment by darktrojan** [comment]
Does this happen every time you start Firefox? There is a bug which causes this to happen _sometimes_, in fact I made a change yesterday which should fix it. (Not released yet.)

**Comment by MichaelIsGreat** [comment]
Hello darktrojan,

So far, yes it has done that each time that I have started again from scratch opening Firefox again!! If, when it does not do that anymore, hopefully I will put a note here to let you know.

**Comment by darktrojan** [comment]
Do you clear your history when Firefox closes? Normally empty spaces would be filled with the most popular pages from your previous sessions (but if there's no history then there'll be no tiles).

If you're expecting pages from only the current session to appear, then I know why that's not happening, and it's because of a change recently.

**Comment by MichaelIsGreat** [comment]
Hello darktrojan,

I confirm just now that this bug now seems to be solved fully! That was really quick!

Great job, once again. Kudos!

**Comment by MichaelIsGreat** [comment]
Well, as of today on 04/13/2016, the problem is solved as I do see the 10 rows and after my pinned tiles, I do see other non-pinned tiles also showing up to fill in the remaining spaces where non-pinned tiles are located after my by set of pinned tiles.
So, so far, so good! I hope it will keep working properly this way and not revert to the previous buggy behavior.

**Comment by MikeUnseen** [comment]
Hi, I just signed up to mention that I am having this same issue. I have mine set to 5x5 and I'm missing five tiles throughout my grid.  This all started about two-three days ago after the most recent update.  This issue occurs both on my desktop and laptop using a synced Firefox account and this is occurring every single time now when I open Firefox and open a new tab.  The first day, the issue was intermittent, then after the first day or so, it became a permanent problem with missing tiles.

Like the OP, I believe the issue is also with tiles that I did not have pinned, but were from frequently accessed pages.

Thank you.

**Comment by MichaelIsGreat** [comment]
Well, as of today 04/13/2016 in the morning, the problem is back as it was before!! 

It is hard to believe that it was solved a couple of hours ago and now, when I get up this morning, this problem is back again!!
I have no idea if you made any changes during this period of time but that is the situation now that is the problem back as it was before! That is I have 10 rows and 8 columns and currently 70 pinned tiles. At the end of the 70th pinned tile on the 9th row, there are two empty spaces plus the full 10th row that should be filled with tiles that are not pinned but instead you do not see anything in these free spaces.
A few hours ago, these free spaces were filled with tiles that were not pinned but now this morning, these free spaces are not filled with non-pinned tiles.
Very strange this changing behavior!

**Comment by MichaelIsGreat** [comment]
Now, as of today 04/13/2016, later during the day, the problem is solved. Will it revert back to when there was the problem, I do not know at all!

**Comment by darktrojan** [comment]
I did ask if it happened every time you start Firefox. Apparently the answer is "no".

The good news is I've already made a new version with a fix, and I'm waiting for it to be approved.

**Comment by michaelg3** [comment]
sorry i just need the new tabs tool. windows updated today & i have no tiles. so sad. tried reinstalling but the page is blank. can choose rows & columns but open a new tab & the page is blank. i cant go on like this...
