### ISSUE TITLE
Option to disable tile drag to prevent false drag instead of click

### ISSUE THREAD

**Issue by Marat-Tanalin** [darktrojan/newtabtools#199]
It would be nice to have an _option_ to completely disable drag-n-drop functionality for tiles. This would prevent users from dragging _unintentionally_ instead of actually intended click. When such false drag happens (due to some small amount of mouse move during performing a click), _click does not happen at all_, so user is forced to click again. Preventing such situations would make the extension more user-friendly. Thanks.

**Comment by darktrojan** [comment]
That's a good idea and something I've been thinking of doing for some time. I've made the changes and I'm going to wait a while to make sure I'm happy with it, then release. Thank you for the suggestion.

**Comment by Dommieking** [comment]
hi, Mr........come up again am blank from your text plz

**Comment by darktrojan** [comment]
I've just released this.
