### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by DonTomas4** [darktrojan/newtabtools#218]
I have problem with encoding. Using Czech language. Usualy UTF8 or microsof 1250. If I save new tile with original name/description, it's displayed everytime OK in new tab. But if I change the description of the tile, after Firefox's restart, than the description is wrong. Specific symbols in my language are replaced by some wrong ones.

Example: Original tab: Wikipeda - otevřená encyklpedie. Renamed tab: Wikipedia - vše co potřebuji. After restart: Wikipedia - v&e co pot#ebuji.

How to make it work?
THX

**Comment by darktrojan** [comment]
This is such a basic bug I can't believe how long it took before somebody noticed it. Should be fixed with the next release, but you might have to redo any bad labels as they'll be saved wrong.

Thank you for reporting.

**Comment by DonTomas4** [comment]
Great, thank you! Hope it will work :-) Will let you know.
