### ISSUE TITLE
notificaion at every startup

### ISSUE THREAD

**Issue by deathtrip** [darktrojan/newtabtools#226]
Everytime i start firefox, i get a notification "New Tab Tools needs to change your new tab page".
Not sure if it's caused by another extension/setting or just a bug.

**Comment by bdplaid** [comment]
me too.  is there a fix?

**Comment by bdplaid** [comment]
what a pita.

**Comment by darktrojan** [comment]
See #156.

**Comment by bdplaid** [comment]
thanks.
