### ISSUE TITLE
"Capture page thumbnail" needs to be under a newtabtools submenu

### ISSUE THREAD

**Issue by PadaV4** [darktrojan/newtabtools#232]
Right now it presents no clue to the user that this option is added by the addon. So right now the first thought is that its a Firefox option. For example the only reason i know the option is put there by this addon, is because googling "Capture page thumbnails" brought me here.. Putting the button "Capture page thumbnails" inside a menu named "newtabtools" would make the purpose of this button much more obvious to the average user.

**Comment by WolfganP** [comment]
Currently using v83b2 and trying to force a page thumbnail, I found this action was implemented already (I didn't know :-) ) but is missing from the NTT Options, Main bar Tool or page Context menu for me. Is there any documentation on when this should appear?

**Comment by PadaV4** [comment]
Well is see the "Capture page thumbnail" option under Menu Bar -> tools. And its there at all times, no matter what's open in the current tab. 
![newtab](https://user-images.githubusercontent.com/5673007/29301321-f71242de-8183-11e7-9ab6-6ae7ab74d71f.png)

**Comment by darktrojan** [comment]
The capture thumbnail action is gone from NTT since Web Extensions have no control over thumbnails. However, as of about a week ago NTT makes its own thumbnails so it might return.

In any case, this issue is no longer relevant as soon as AMO finally reviews the next version, so I'm going to close it.

**Comment by WolfganP** [comment]
Thanks @PadaV4 for the screenshot.
@darktrojan thx for the explanation, it makes sense as I moved to the latest beta version. Anyways, some tiles still show no thumbnail (just a dark gray square shown), is there any way to force the capture with the latest NTT?
