### ISSUE TITLE
importing settings fails when prefs.json is too long

### ISSUE THREAD

**Issue by schaedi** [darktrojan/newtabtools#237]
I found that importing settings did not work for me. I set up my newtab page with 7x8 tiles and a lot of settings. These settings can not be re-imported after being exported from newtabtools.
I debugged export.jsm and found, that the line 246 "utf8Stream.readString(8192, data);" in function readZippedJSON gave me only part of my settings-file, what I assume is the buffer-size (that number 8192) is less than my settings-lenght. Parsing this data fails, no import-dialog is shown.

**Comment by darktrojan** [comment]
Okay, I see the problem. It looks like I forgot to keep reading once the buffer is full. I'm surprised your file is big enough to have a problem, but here we are.

I've got a fix which I'll put in the next version. Thank you for writing a helpful report!

**Comment by darktrojan** [comment]
I've just pushed this to the add-ons site for review. I meant to do so a lot earlier, but forgot! Sorry.
