### ISSUE TITLE
Script Unresponsive Message

### ISSUE THREAD

**Issue by M3t0r** [darktrojan/newtabtools#239]
Firefox gave me the message that a script was unresponsive, if I'd like to [Stop] [Debug] [Continue] it.

The script was [chrome://newtabtools/content/fx-newTab.js:499](https://github.com/darktrojan/newtabtools/blob/VERSION_76/content/fx-newTab.js#L499)

I have a 4x5 grid with 16 pinned tiles. 

I got this once before (Line 495 I think), but I can't reliably reproduce this. I'd say there is a general sluggishness in opening NTT and leaving to a clicked tile and on these two occasions a timeout was reached.

Firefox 50.1.0, Windows 10, uBlock Origin, Tab Mix Plus, Reddit Enhacement Suite, PassIFox, NTT 76, FoxyProxy Standard, "Emoji Cheatsheet for GitHub, Basecamp etc."

I don't have any experience with debugging addons, but let me know how I can help you.

**Comment by darktrojan** [comment]
This happens when you click on a tile and expect that page to load, correct? That's very weird.

There are a few things I've thought of that might fix it, so I'll try those when I have some time.
