### ISSUE TITLE
Will this addon be compatible with WebExtensions?

### ISSUE THREAD

**Issue by TheFireRed** [darktrojan/newtabtools#241]
I'm looking for addon alternatives for the day Mozilla stops supporting previous addons.

**Comment by darktrojan** [comment]
Unlikely. I want it to keep working because I use it all the time, but frankly webextensions are not and will not be capable of doing a lot of what New Tab Tools does.

**Comment by yfdyh000** [comment]
[Bug 1234150 - Support overriding newtab page from a webextension](https://bugzilla.mozilla.org/show_bug.cgi?id=1234150)

**Comment by yfdyh000** [comment]
Bug 1234150 was fixed.

**Comment by darktrojan** [comment]
Closing this in favour of #250.
