### ISSUE TITLE
Move thumnail image around in Edit Tile

### ISSUE THREAD

**Issue by MrUnknownGuyAC** [darktrojan/newtabtools#248]
While grabbing images from an image search, I'm mildly annoyed that I can't find the perfect image for the tile's thumbnail. And when I do, it's always off center or it doesn't even fit!

Would it be possible to adjust the position of the thumbnail image so I can specify not to place the image in the center and maybe even scale the image down as well? Some thumbnail images are too big so it just shows a portion of the image.

![Example of huge thumbnail](https://cloud.githubusercontent.com/assets/19784752/24989094/51b3315e-2049-11e7-8eaa-1c31a26de491.PNG)

**Comment by rusins** [comment]
Yes, I too am annoyed that the image isn't centred vertically :(
