### ISSUE TITLE
Transition to WebExtensions status

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/newtabtools#250]
I'm working on a WebExtensions version of New Tab Tools. Because the existing version reaches so far into Firefox internals, and because the WebExt API is so hopelessly limited, things will never be the same again. Here's where I'm at. This issue will be updated as things progress.

A beta of New Tab Tools as a WebExtension is available at https://addons.mozilla.org/firefox/addon/new-tab-tools/versions/beta. You are welcome to try it, but be aware that things could explode at any time! The beta should automatically update, but you will have to manually return to the main release channel eventually. To go back to normal New Tab Tools, download it again from https://addons.mozilla.org/firefox/addon/new-tab-tools.

## Done so far:

- Pinned tiles
- Tile title, image, background colour
- Page background
- Grid layout preferences
- Copying pinned tiles and preferences from old extension
- Tiles from browsing history
- Option to hide tiles from history
- Localisation
- Recently closed tabs

## Needs to be done:

- Context menu items

## Might make it (Firefox changes might be required):

- **Page thumbnails** [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1246693)
- Dragging URLs from the Firefox UI to form a tile
- Site icons
- Loading images from the web for tiles and background
- Making all history available instead of one URL per domain [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1361899)

## Very unlikely to make it:

- Launcher from about:home
- Capture Page Thumbnail button
- Exporting and importing settings (*might* return in some form later)

**Comment by nt1m** [comment]
@darktrojan 

> Dragging URLs from the Firefox UI to form a tile

Doesn't the HTML5 drag and drop API support this ?

> Site icons

If you don't mind using online services, you can try: https://ucygetfavicon.appspot.com/

> Loading images from the web for tiles and background

Why does this need Firefox changes?

> Recently closed tabs

This seems straightforward to implement: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sessions/getRecentlyClosed

> Exporting and importing settings (might return in some form later)

You can probably rely on sync storage for now.

**Comment by darktrojan** [comment]
Oh hi Tim, thanks for the input!

> Dragging URLs from the Firefox UI to form a tile
> Loading images from the web for tiles and background

The problem with these two is that the moz-extension page is unprivileged. I can get dragged URLs from other pages fine, but from the UI the transferred data is just "". And if I load an image from the web and make a blob from it (the tile images are stored locally) I hit CORS errors. :-/

> This seems straightforward to implement: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/sessions/getRecentlyClosed

Somehow I've missed seeing this altogether. It's exactly what I need, I think.

**Comment by nt1m** [comment]
Hi Geoff,

For Loading images from the web for tiles and background, have you tried using the webRequest API and including the <all_urls> permission?

**Comment by yfdyh000** [comment]
About `Dragging URLs from the Firefox UI to form a tile`, https://github.com/eoger/tabcenter-redux/commit/684b809f2c733cb4a390e89aee73470bbe96031d may be useful.

**Comment by yfdyh000** [comment]
A question, would you make a pure-WebExtensions? It is currently an [Embedded WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Embedded_WebExtensions) that [will be disabled in Firefox 57](https://bugzilla.mozilla.org/show_bug.cgi?id=1363897) (`extensions.legacy.enabled`), and the "webextension" directory cannot be independent load and working so far.

**Comment by darktrojan** [comment]
Of course. In fact the only thing that stops it running that way is one line I need to swap with the commented line above it.
