### ISSUE TITLE
Newtabtools (WebExt) does not show up on new tab

### ISSUE THREAD

**Issue by BubiBalboa** [darktrojan/newtabtools#253]
I have deactivated SuperStart, restarted FF and activated Newtabtools. When I open a new tab I get Firefox new tab page. Am I missing something?

**Comment by darktrojan** [comment]
Sometimes it does take a few seconds after starting up before Firefox realises it should show a different new tab page. That's all I can think of.

**Comment by darktrojan** [comment]
Sometimes it does take a few seconds after starting up before Firefox realises it should show a different new tab page. That's all I can think of.

**Comment by BubiBalboa** [comment]
Hmm, the regular version works. I'll try again later as the WebExt version matures. If it still won't work then, and after more in-depth trouble shooting on my part, I'll let you know. Thanks for your work.

**Comment by zJelly** [comment]
Are you on Firefox stable? (currently version 53.0.2)
Assuming I'm reading [Bug 1234150](https://bugzilla.mozilla.org/show_bug.cgi?id=1234150) correctly, using WebExtensions to override about:newtab is only possible in Firefox 54, which is currently in the beta branch

**Comment by BubiBalboa** [comment]
That must be it. So it will fix itself, which is nice. Issue closed, I think.

**Comment by darktrojan** [comment]
Huh, that's interesting. I thought I had tested it on 53, but it must've been 54. Also, I've looked at that bug several times and clearly not taken any notice of when it was fixed. Sorry!
