### ISSUE TITLE
You plan to publish to the Chrome Web Store when WebExtension is released ?

### ISSUE THREAD

**Issue by JrsM30** [darktrojan/newtabtools#259]
Very good complement! It would be great to have it for Google Chrome too! Thank you for developing! :)

**Comment by darktrojan** [comment]
It could happen, but I'm not going to say yes or no yet.

**Comment by darktrojan** [comment]
I'm marking this as "future" because New Tab Tools will run with some modifications on Chrome/Chromium, but some major parts are broken. Such as anything to do with images.

**Comment by JrsM30** [comment]
Thanks for the dedication to launch a version for Chrome in the future, thank you!

**Comment by darktrojan** [comment]
Just so you know, I'm not promising anything. But it's closer now than it has ever been.

**Comment by darktrojan** [comment]
https://chrome.google.com/webstore/detail/new-tab-tools/gfonmeedigdbjpgpeojioadpimflbogh

I wouldn't call it perfect, but there it is.

**Comment by JrsM30** [comment]
It was very good! Great job! Thank you very much!

**Comment by DanaMW** [comment]
Thank you.
