### ISSUE TITLE
NewTabTools not working Need advice

### ISSUE THREAD

**Issue by abhichakravarty** [darktrojan/newtabtools#261]
As i updated to firefox 54 newtabtools stopped working. Ihave tabmix alsso. but i need some of its features also. So how can i stop only new tab part of tabmix plus. Pls advise

**Comment by TheNightProducer** [comment]
Hello, exactly the same problem exists also with Firefox 64bit v56.0a1, please fixes this problem as fast as possible because I would not be without your addon!
Here is a link why the problem exists -> https://support.mozilla.org/en/kb/modernisierung-firefox-add-on?as=u&utm_source=inproduct
MFG

**Comment by WolfganP** [comment]
I observed the same behaviour, New Tab page appeared blank after updating from FF55.0 64 bits with multiprocess enabled to v56b1 (I'm on the beta channel btw)

**Comment by darktrojan** [comment]
@WolfganP see my comment on #267. @TheNightProducer that might be the problem you see too.
