### ISSUE TITLE
Click on favicon of the attached tile removes it

### ISSUE THREAD

**Issue by RblSb** [darktrojan/newtabtools#264]
OSX 10.9, FF dev edition 55,  tabtools v81, nonwebext.
Enable site icons to reproduce it.
Is this problem in the version for webext? If not, I'll go over to her.

**Comment by darktrojan** [comment]
Interesting. Reading the code I can see you're right, but I wonder why it's taken so long for anyone to notice.

The web extension version doesn't have favicons, so this isn't a problem for it.

**Comment by RblSb** [comment]
Click on the icon turns out extremely rarely and it's hard to immediately understand what the problem is. When you return the site back it seems that everything works without problems.
