### ISSUE TITLE
If an imported "Saved image" filename is too long, the "Set" button area is pushed off its hitbox (83b1)

### ISSUE THREAD

**Issue by eberhardweber** [darktrojan/newtabtools#265]
When adding a "Saved image" for a tile in New Tab Tools version 83b1, if the image filename contains too many letters, the "Set" button adjacent to the loaded image filename does not activate by pressing. This is caused by the "Set" button being pushed to the right by the filename, but its hitbox staying put.

The amount of letters required in the filename for the button to move is around 48. After that, the button begins to move, whereas the hitbox stays - if you hover over the original placing of the button, the now-moved button highlights and can be clicked in its original place.

**Comment by darktrojan** [comment]
I'm aware of this and trying to find a good solution. Thanks.
