### ISSUE TITLE
URL bar is not cleared when a new tab that loads New Tab Tools is opened (83b1)

### ISSUE THREAD

**Issue by eberhardweber** [darktrojan/newtabtools#266]
Since the current new branch of New Tab Tools (83b1) does not currently seem to replace _about:newtab_ in Firefox outright, I currently use the add-on by setting the Home Page in Firefox's General settings as "moz-extension://31c4a10e-7a99-4adb-a7cd-786bf415732a/newTab.xhtml". That way, whenever I open a new tab, New Tab Tools loads.

However, this brings me to the very unfortunate usage loop of having to erase that selfsame address from the URL bar every time I want to write something into it - which is, let's be honest, extremely often. This has hampered my usage of the browser somewhat. 

Looking into the situation, I learned that a legacy add-on (in the process of being ported) called [New Tab Override](https://addons.mozilla.org/en-GB/firefox/addon/new-tab-override/) provides an option to erase the URL bar as a new tab containing an address is opened - could this function be incorporated into the WebExtension version of New Tab Tools?

It would be very advantageous for New Tab Tools to perform this action by itself if it cannot simply replace _about:newtab_ due to being a WebExtension. Of course, if the add-on is going to be able to directly replace _about:newtab_ later, which by default comes with no URL in the URL bar, then this function is probably not needed.

**Comment by Asteaguinity** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1372996

**Comment by darktrojan** [comment]
I can't do anything about it, or I would have, long ago. It's very annoying.

**Comment by darktrojan** [comment]
Closing this issue because there's also #274 and we don't need two issues.
