### ISSUE TITLE
Export/import settings not importing thumbnails

### ISSUE THREAD

**Issue by np422** [darktrojan/newtabtools#268]
Hello,

(I'm using firefox 56.0b2 (64-bit) on mac)

I was trouble-shooting a very annoying browsing issue that were ok using a clean profile but not with my current set of add-ons. I tried disabled most of my add-ons in an attempt to bisect the misbehaving add-on.

Newtabtool wasn't the guilty one. As I'm very fond of my newtabtool enhanced page I had first made and an "export settings" and saved the zip-file.

After finding and removing the troublesome add-on I re-enabled newtabtools and all my beautiful thumbnails were gone, I tried to import settings from the zip-file. Background-image and some other settings was imported, but no thumbnails. Screenshot: 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/1257517/29240703-31595738-7f5a-11e7-96a6-6888b6072024.png">

So, I unziped the export and examined .... There seems to be something peculiar about the prefs.json export, see the screenshot of ```python -mjson.tool prefs.json``` where I've removed some of my clients internal pages I don't want to disclose.
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/1257517/29240639-b2b441c8-7f58-11e7-9d7f-b1ef19835d61.png">

After some editing of json to make it look like what I suspected was the intended format .. 
<img width="544" alt="image" src="https://user-images.githubusercontent.com/1257517/29240678-99b38c50-7f59-11e7-8f9c-74e8bcb330e1.png">

I zipped it back together and tried to import it once more, but with no success.

At this point I gave up and realized that I really have no idea what I'm doing or what the prefs.json format is supposed to be and I decided to put my pinned pages back one by one, the thumbnails and urls were after all available in the zip-file.
 
As we currently live in interesting times with regards to firefox add-ons development I don't expect this issue to have any kind of priority, but I thought I should let you know about my findings. 

Thank you for a useful and much appreciated firefox add-on.

**Comment by np422** [comment]
Uninstalling + restart + reintall brought all my pinned pages back, phew!
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/1257517/29240838-84739de6-7f5c-11e7-8f3a-6eef6726f91a.png">

**Comment by darktrojan** [comment]
Okay, a few things indicate to me you're suffering from the same issue as the others, which is caused by a new feature to Firefox that seems to be active for only some people, including, AFAICT, new profiles.

The exported format is correct, that mess of a first line is JSON-encoded twice because the pref usually has a JSON string in it. (Firefox prefs can only be strings, numbers, or boolean.)

**Comment by np422** [comment]
Twice encooded json, when I read it I suddenly got a craving for the local Chinese restaurants dish "twice cooked pork".

I agree that the root cause of my problem is likely the same as other 56b users, I'll close this ticket as a duplicate.
