### ISSUE TITLE
Set the background to black is it possible?

### ISSUE THREAD

**Issue by tipar** [darktrojan/newtabtools#269]
I would like to know if it is possible to set the background to black, I mean when I open new tab the background is black no matter what I modify on the section background. Thanks.

**Comment by darktrojan** [comment]
I don't understand the question. The easiest way to get a totally black background (assuming the dark theme isn't dark enough for you) is to make a black image and set it as the background image.

**Comment by flotteur** [comment]
Maybe you are looking for the Dark theme in the options?
