### ISSUE TITLE
Is there a way to set NTT as homepage across all synced machines?

### ISSUE THREAD

**Issue by jagmoreira** [darktrojan/newtabtools#271]
I set up NTT as my home page, but that doesn't work across different machines. Even if you use Firefox Sync to share add-ons, the installation paths will be different.
Here's what it looks like on my 2 machines:
* moz-extension://**da533afb-d2c7-4739-9412-14c298c1d0d4**/newTab.xhtml
* moz-extension://**4e150090-e7d1-4d41-a00c-49cb46ad7ee7**/newTab.xhtml

Is there a way to set NTT as homepage across all synced machines?

**Comment by darktrojan** [comment]
In short: no. The address is randomly assigned when you install. There is a chance that in the future I'll be able to give the page a more sensible address, but don't hold your breath.
