### ISSUE TITLE
new tab page overridden is not canceled when the extension is disabled

### ISSUE THREAD

**Issue by yfdyh000** [darktrojan/newtabtools#272]
83b2 in Firefox 56 beta.
New tab page is blank with `moz-extension://d9c9724a-83d3-471e-a53b-ed493ad39986/newTab.xhtml` on urlbar after the extension be disabled, until the browser restart.

**Comment by darktrojan** [comment]
I expect this is a Firefox glitch. It works for me, and in any case there's nothing I can do about it, so I'm going to close this.
