### ISSUE TITLE
Isn't working - New tab page just goes to Firefox's defaults after latest update

### ISSUE THREAD

**Issue by lambdaman121** [darktrojan/newtabtools#273]
Extension automatically updated to the WE thing, and was working fine.

Closed browser, opened an hour or so later, and the new tab page is Firefox's default one.

Reinstalling the extension from the store seems to work (extension settings are the same as I set them), but once I close my browser and reopen it, it just goes back to Firefox's default one.

Tried turning Auto updates off, didn't help.

Using FF 55.0.3, NewTabTools 82.1

Repro: *shrug*, update the extension?

No other extensions installed that should be affecting the new tab page.

**Comment by lambdaman121** [comment]
Uninstalling and reinstalling seemed to do the trick (hopefully)

Should've thought of that before creating an issue, sorry =(

**Comment by darktrojan** [comment]
I'm going to blame Firefox, but this *shouldn't* happen again now you've updated to the WebExtension.
