### ISSUE TITLE
Icons are fuzzy after update

### ISSUE THREAD

**Issue by Kie16** [darktrojan/newtabtools#275]
Before the update, icons were fine and full HD, however now, even though it is the same image; it looks fuzzy.

Also now this is in the search bar in a new tab: moz-extension://38cbaad1-e5bf-41af-8265-083b3343d8b7/newTab.xhtml

**Comment by darktrojan** [comment]
Are you talking about images that have been copied automatically from the old version, or ones you have added since the update? I don't know why the first case would happen, but I've found a bug in the second and fixed it.

**Comment by Kie16** [comment]
Yes, after the update some icons were removed so I added it again but they are fuzzy

**Comment by darktrojan** [comment]
Should now be fixed in v83 (latest release).
