### ISSUE TITLE
everything changed

### ISSUE THREAD

**Issue by firejack007** [darktrojan/newtabtools#277]
Custom icons I had are gone. Websites are still in order that I customized before but now showing websites as icon. Large tabs, rows and columns changed. No way to configure (edit)? Where's the control? Looking in about:config, I see newtabtool settings still there but now overriding scripts titled 'newtabpage' added.

**Comment by darktrojan** [comment]
Yes there were big changes but most of what you describe is unexpected. Could you post a screenshot of what you see?

**Comment by DanaMW** [comment]
when i added the updated newtab tools that's how it was at first you just have to re add the images  and it should be fine.

**Comment by darktrojan** [comment]
@firejack007 also, in response to the review you just posted:

> someone had the bright idea that something needed to change

Yes. Somebody that works at Mozilla. Not me.

**Comment by firejack007** [comment]
Was working fine just 30 min ago with Firefox 55.03.  I use custom icons and when I opened Firefox today it was working. It changed as I was using Firefox and clicked on a new tab I was shocked to see the configuration had changed. This is what it looks like now.
![2017-08-28_18-52-20](https://user-images.githubusercontent.com/31423838/29798417-725ed21a-8c22-11e7-9b0b-aee7f1ca971e.jpg)

**Comment by darktrojan** [comment]
That's the Firefox built-in page. Try disabling and re-enabling NTT. If that doesn't work try restarting Firefox.

I'm sure there's some bug in the Firefox code which has stuffed up your upgrade (based on other similar things I've seen happen before), but I've never found it.

**Comment by firejack007** [comment]
Thank you I'll give that a try.

**Comment by darktrojan** [comment]
Your new tab page address should change to `moz-extension://<letters and numbers>/newTab.xhtml`.

**Comment by firejack007** [comment]
I've disabled NTT and restarted Firefox. Took 2 or 3 times but finally came back. Controls are back. Just have to redo some of the icons/links.
![2017-08-28_19-46-40](https://user-images.githubusercontent.com/31423838/29799545-e6c9cb8a-8c29-11e7-8690-bfc31233c6c1.jpg)

**Comment by AuroraGriffin** [comment]
I am having the exact same problem.

"moz-extension://<letters and numbers>/newTab.xhtml" does work. Just gives me an invalid address error.

And I don't think I not NTT. Not even sure what that is. So, cannot disable and re-enable whatever that is.

I hope this get fixed soon ...

**Comment by firejack007** [comment]
What I found is after resetting firefox and deable/enable NTT, when you open a new tab the full link is in the address bar. Copy that and put as your start page under Firefox/options. 

Only problem I'm having now is that when firefox starts i'm getting a blank page. if I open a new tab everything works.

**Comment by DanaMW** [comment]
I made my start page about:blank  in FF Options and that allowed NTT to work in FF 56 B

**Comment by AuroraGriffin** [comment]
"I made my home page about:blank in FF Options and that allowed NTT to work in FF 56 B".

I just tried this. Didn't work.

**Comment by DanaMW** [comment]
I did have to restart firefox  a few  times before it cleared up,  I know that sounds  weird but I just left it messed up and after  the 2nd or 3rd time i started FF developers it came up correctly.  I put it on Firefox being all weird during the transition, Sorry it did not help.

**Comment by darktrojan** [comment]
Using New Tab Tools as your home page does sometimes just have a blank page when you start Firefox. This is because it tried to load the home page before starting the extension. There's nothing I can do about it, sorry.

It seems to be a bit more reliable in Firefox 56/57, so hopefully they've actually fixed something and it's not just my imagination.

**Comment by AuroraGriffin** [comment]
Well, I tried again. I changed it to Blank, then closed and reopened FF several times, changed it back to newtab, and restarted again, and it's still showing the FF Default. >.<

**Comment by alxpl** [comment]
> Well, I tried again. I changed it to Blank, then closed and reopened FF several times, changed it back to newtab, and restarted again, and it's still showing the FF Default. >.<

In my case I had to reinstall from mozilla add-ons site (without disabling or removing it first).

**Comment by AuroraGriffin** [comment]
Well, .... I'm up to look up something before heading out for the morning, and it's _still_ the FF default.

**Comment by AuroraGriffin** [comment]
UPDATE: Okay, I was able to get the method of changing your thing to the "moz-extension" thing. I discovered the right version of this work around by accident, when I opened a new Tab and my NTT Page popped up. So, I copied and pasted that into my FF Start-Up Options and I'm back on track again. ^_^

**Comment by AuroraGriffin** [comment]
"If you have a blank page when starting Firefox, just click on the homepage icon (little house) on the upper right of the menu and your homepage with icons will show up."

Oh, I know I can do that, but for now, the Blank Page is okay. It says "New Tab", but looks blank. But if I open a second New Tab, I get my lay-out.

II think I'm fine with it. If I get onto the wrong page and end up with a browser crash from the URL, I don't think I want FF to open automatically to that page again. LOL!
