### ISSUE TITLE
Pretty much broken all of a sudden

### ISSUE THREAD

**Issue by TehKaoZ** [darktrojan/newtabtools#278]
I have been using it for months and all of a sudden it just stopped working. I tried re-installing but no change, I am simply stuck with the default new tab page. 

The only way I can get it to work is by going into Add-Ons and manually disabling and re-enabling the addon but I have to do this every single time I start up firefox because as soon as I close it, it reverts. 

Basically, it seems like it's disabling the addon by itself whenever I close my browser. 

EDIT: I believe I have figured it out and it is an incompatibility with Blackfox V2

**Comment by darktrojan** [comment]
> I believe I have figured it out and it is an incompatibility with Blackfox V2

That seems likely. They'll be fighting over who gets to be the new tab page. Can you disable just the new tab feature of Blackfox?

**Comment by TehKaoZ** [comment]
I do not believe so.

For now I have installed a different black color browser appearance that doesn't interfere with the tabs page and all seems fine.  Maybe I will drop a line on that page requesting a disable feature at some point. 

Thanks for the reply
