### ISSUE TITLE
Not working in FF56.0b6 (64-bit)

### ISSUE THREAD

**Issue by GDZed** [darktrojan/newtabtools#279]
Hi.
I use your extension for a long time but now it not work. When I open new tab in FF - only blank screen with gear in upper right. I try disable all extension except of NTT restart FF but nothing changes.
_FF dev. 56.0b6 (64-bit), NTT 84.0b1_

**Comment by darktrojan** [comment]
Restart Firefox a few times. Firefox has some sort of cache for their new extension system and it doesn't work right. :-/

**Comment by GDZed** [comment]
I did it many time and periodically clear FF cache from browser and local from windows but unsuccessfully

**Comment by darktrojan** [comment]
Uhh, okay, try uninstalling New Tab Tools and then reinstalling.

Sorry, I don't really understand what causes the problem, so I don't know exactly how to fix it.

**Comment by GDZed** [comment]
I also tried this - but the same negative result.
