### ISSUE TITLE
What to do if your tile images were not imported properly

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/newtabtools#281]
I made a dumb bug. This one's actually my fault, unlike the other one I've spent all day chasing.

If none or only some of your saved tile images remain after updating to version 82.1 here's what you can do:

- ~~Wait until version 82.2 is approved by the addons.mozilla.org reviewers. No promises over when this will happen, the last time took 3 weeks.~~ Update to version 82.2.
- Open a new tab with the New Tab Tools page on it.
- Open the web developer tools (press F12), then go to the Storage tab.
- Find this item `newTabTools (default)` in the left panel, right-click and delete it.
![devtools](https://user-images.githubusercontent.com/1540303/29822191-b7bf977a-8d1e-11e7-98a6-14ffd9700467.png)
- Restart Firefox.

This should re-import your saved thumbnails from before. **But** it will destroy any you've made since version 82.1, and the locations of any tiles you've moved around since then. I warned you. Also, don't do this in version 84 or later. It won't work.

**Comment by EpicWolverine** [comment]
I updated to 82.2 and still have this issue. I cannot apply the fix since Dev Tools shows there is already nothing stored in Indexed DB. I've reverted to 81 for now.

**Comment by darktrojan** [comment]
@EpicWolverine I've just re-read this and realised it's the same issue I've seen elsewhere. Do you have cookies disabled? If so, create an exception for the `moz-extension://[letters and numbers]` page in Firefox preferences.

**Comment by EpicWolverine** [comment]
No I have cookies enabled. I just tried doing what you suggested anyway and there was no change.

**Comment by darktrojan** [comment]
Do you have IndexedDB enabled? Check `dom.indexedDB.enabled` in `about:config`.

**Comment by EpicWolverine** [comment]
Yes, IndexedDB is enabled.
