### ISSUE TITLE
Low-res thumb-nail scaling

### ISSUE THREAD

**Issue by okdana** [darktrojan/newtabtools#282]
Hey there. On Firefox 55, using 84.0b1 (and i think earlier), i get really bad, low-quality scaling on custom thumb-nails:

![screen shot 2017-08-29 at 11 37 34](https://user-images.githubusercontent.com/122095/29832645-81342a60-8cae-11e7-88db-9a33850f6dad.png)

That's the 'out-of-the-box' appearance — in fact it looks even worse than that for me normally because i use Stylish to make the thumb-nails fill the whole box.

It seems like maybe the thumb-nails are scaled to a fixed (small) width? Is that what's happening? Is there anything i can do about that?

PS: Sorry the WebExtensions fiasco is causing you so many problems. Looks like a lot of people are upset with the extension when it's not even your fault. Sucks :/

**Comment by h0rn3z0r** [comment]
Any solution to this, before the update comes?

**Comment by darktrojan** [comment]
84? That doesn't look right, for 84. It makes square thumbnails and fills the box with them (that is, the edges would be cut off). I'm wondering if those are images from an earlier version that got stuck somehow?

**Comment by okdana** [comment]
Sorry, they're custom thumb-nails that i'd generated with Firefox's screen-shot feature.

Background: After upgrading to 84 I followed the instructions in #281 to delete my IndexedDB data, thinking that that would fix it, but instead it completely blew away all of my settings. The picture i attached above is what i'm looking at now after re-applying all of those previously generated thumb-nails. (Just for reference, the 'native' size of these images is about 1700x2400.)

Since you mentioned it, i tried deleting one of my custom images and letting the extension generate a new one. The scaling quality on that one is better, though it is apparently still a fixed size, which looks bad if the tiles grow too large:

![screen shot 2017-08-29 at 16 09 31](https://user-images.githubusercontent.com/122095/29844335-8da3125e-8cd4-11e7-99e1-6670c357789f.png)

`.custom-thumbnail` has a CSS rule that modifies its `background-size`, &al., which explains why the custom images don't fill the whole tile. Not sure if that's deliberate. (As long as i can override it with Stylish it doesn't really bother me either way.)

**Comment by darktrojan** [comment]
Okay, #281 isn't going to do anything for you, that fix isn't in 84b1. 84 doesn't know anything at all about the old extension. I should've mentioned it but I wasn't thinking about 84 at that point. You could go back to 82.2 when it's available, or get your old images from the `newtab-savedthumbs` folder in your profile directory and re-add them.

Yes, the new generated thumbs are always 300x300. I think I'll have to change that. And yes, that CSS change is deliberate.

**Comment by darktrojan** [comment]
Should be fixed in 83 (latest release) and 84b2 (latest beta).
