### ISSUE TITLE
A letter from a user

### ISSUE THREAD

**Issue by virial** [darktrojan/newtabtools#283]
This is not an issue, I just needed a way to reach out to darktrojan and give other users/devs an opportunity to offer their gratitude.

I am an avid newtabtools user. I rely on this extension every day of my life and am quite appreciative of its existence and continued development. 

As you may know, Mozilla is updating its method for developing extensions so that they are less likely to break when Firefox is updated. More can be read here: https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing?as=u&utm_source=inproduct

Starting in November 2017, Firefox extensions will be required to be developed using this new framework. Legacy extensions will be automatically disabled. I would like to take this opportunity to say that my browsing experience would drastically decline without your hard work. On behalf of thousands of users, I strongly encourage the continued development of newtabtools. If financial barriers make this difficult, I would be happy support the cause when possible. It would really mean a lot.

I realize add-on development rarely gets the appreciation it deserves, so I hope this provides any needed reassurance that your dedication does not go unnoticed.

**Comment by chronvas** [comment]
Also this addon is now marked as "Legacy" on the Firefox Add-ons Manager

**Comment by MrChris123** [comment]
Rather surprised this hasn't had more support. 

Since the recent update of Firefox, NTT has stopped displaying any tiles, and all I have is a list of recently closed tabs along the top. This has made me realise how much I have relied on NTT.

I would like to take this opportunity to thank darktrojan and co for all their work, and I hope development continues under the new Firefox framework

**Comment by darktrojan** [comment]
@MrChris123 That's a bug I haven't heard before. Care to open a new issue, and post the contents of `[your profile folder]/browser-extension-data/newtabtools@darktrojan.net/storage.js`?

**Comment by MrChris123** [comment]
@darktrojan - I assumed it was part of the https://github.com/darktrojan/newtabtools/issues/280 issue.

I have recently uninstalled NTT and then reinstalled it. Would that clear out the storage file? Anyway, the content of it are 

`{"version":83,"versionLastUpdate":"2017-09-04T10:42:15.624Z"} `

I am running Firefox 55.0.3 (32-bit) on Win 7 x64. Do you still want me to open an issue?

**Comment by darktrojan** [comment]
@MrChris123 That's *odd*. Perhaps try #281 and if that doesn't work, by all means create a new issue. I'm going to close this one.

Thanks for your words, @virial.
