### ISSUE TITLE
Unpin and Remove buttons show on all tiles all the time, fewer columns available after update

### ISSUE THREAD

**Issue by randomname42** [darktrojan/newtabtools#285]
To start off I want to say this is a great extension and I'm sorry to see it's having problems after the update to the new Firefox extension type. 

I did get the update working after following instructions (yay!). But now all tiles have the Unpin and Remove buttons showing all the time. It's ugly, but more importantly all those buttons all over are very distracting and make it impossible to find the right tile at a glance. 

Being able to have so many tiles on display yet have the appearance remain so simple and uncluttered is one of the things I have always loved about this extension.

I have on occasion had those buttons show on all tiles, but there was a way to turn them off. Now there seems to be no way to do that. Was the option to turn them off intentionally removed? I don't understand why that would be taken out.

Was the maximum amount of columns also intentionally reduced? I used to have 8 rows and 12 columns. I believe that back when I set that I had to type 12 in manually (instead of using the little up/down arrows) and then hit enter. But in previous versions I had 12 columns, and that was perfect for a 1920x1080 monitor.

Now with the new version it won't take above 10 columns even by typing and hitting enter. In fact, that resets it to 3 columns the next time you open a new tab. Could the max for that please be increased? 

Increasing the number of rows instead shrinks the preview images so much more than having extra columns does. It also messes with the arrangement of tiles which I have gotten used to over a very long time (where each specific tile is in each row, and what row they are on) and to be honest that messes me up quite a bit especially in combination with all those Unpin/Remove buttons all over.

I understand this must be much lower priority than the problems people are having even getting the new version to work in the first place.

**Comment by darktrojan** [comment]
The pin and remove buttons are now hidden if you disable tile dragging. I've connected them together to create a kind-of "read-only" mode, and I should update the label on the checkbox but I haven't gotten around to it. In an upcoming version there's a new button in the bottom corner for toggling the mode on and off with one click. I've found it quite handy since I made it.

You're right, the number of rows and columns is currently restricted to 10. I did it when I had to totally  rewrite the prefs system, to check the number isn't something ridiculous. I guess there's no real reason the upper limit couldn't be 20, so I'll raise it to that.

I do wonder about the performance impact of having 96 tiles though. Is it a bit sluggish, or are you running a supercomputer?

**Comment by randomname42** [comment]
I have a fast pc for gaming and use 64bit Firefox (would 64 vs 32 bit make a difference, btw?), so I hadn't thought about a large amount of tiles potentially causing slowdown.

I was curious about sluggishness myself so when I saw a relative today I tested that on their laptop (Windows 8, Core-Duo, 32bit Firefox).  I had to borrow it for a while some time in the past, and they never use Firefox, so it still had an old version of Firefox and an old version of the extension that I could test 8x12 on.

When I first increased it to 8x12 there was a delay of I'd say less than a second before the new tab page fully loaded. About half the tiles showed up right away, then the rest after the delay. After that loading new tab pages seemed to come up instantly. 

The initial delay might just have been the additional tiles being added from increasing the number of rows/colums. That laptop is often a sluggish to begin with anyway, so I don't know how useful a test that was for you.

If you're worried about it becoming slow with too many tiles though. I'd suggest a warning message when someone puts in a large amount of tiles, that it many cause some slowdown.

About combining the unpin/remove with the tile drag setting. I understand the thinking on that and the desire to simplify. But I always kept dragging on because it was hard to accidentally drag a tile around, and having it always on was convenient. 

On the other hand it was very easy to accidentally unpin/remove a tile if those buttons were showing (and I've accidentally done both a number of times) so having that off with drag on was the best of both worlds.

Something I've considered suggesting in the past is to (if it's even possible) move the unpin/remove options to the menu that shows up when you right click a tile (or at least an setting to put them there). Specifically because that would eliminate accidentally unpinning/removing a tile with a single misclick, and remove the need to toggle a setting every time you want to update your tiles.

So pros: No more accidental removing/unpinning tiles. 
No need to toggle settings to enable that either. 
It naturally fits with how many things in Firefox work (right click to change options). Actually, my first instinct back when I first installed the extension was to right click a tile to find an option remove it.

Con: A 100% guarantee people would be wondering where those went.
There would have to be some sort of message on the settings screen telling people to right click tiles.
People tend to hate change in general, and that is a significant change.

I'm guessing it's unlikely you'd do that, tbh.

There are however two other things with right clicking that I really think could make the extension even more convenient to use. (I should maybe put these in a separate issue, but since I'm talking about right click options anyway it seems better to put them here).

Right now to add a site you have copy the address, switch over to a new tab page, click the gear, paste the address, and drag the tile into the position you want.

So I'm suggesting the ability to right click on any page you are on, and have an option to add the current site address to a tile on the new tab page (no copy/paste needed). Also, option to add a custom title right away (no having to go through the gear menu to rename it). And bonus points for having an option to put it into the position you want (what/row column) to avoid having to do manual dragging into position. 

Plus an option to either insert the tile into that position and slide everything over, or replace pinned tile in that position. That could be useful for updating tiles when sites change their address format (for example, Twitch loves to do this, and I have had to update my pinned tiles for people's past broadcasts several times).

Being able to right click on a specific tile to update address/title for that tile is also something I have wanted to be able to do ever since installing the extension. A choice to replace current pinned tile, or insert a new tile and slide everything over to the left would also be pretty useful.

**Comment by darktrojan** [comment]
> Something I've considered suggesting in the past is to (if it's even possible) move the unpin/remove options to the menu that shows up when you right click a tile (or at least an setting to put them there).

This was a thing. Now I can't, … well I sort of can but it has issues.

> So I'm suggesting the ability to right click on any page you are on, and have an option to add the current site address to a tile on the new tab page (no copy/paste needed).

Working on that, in a way. Wouldn't it be great if I could've spent time developing things like this instead of spending months rewriting stuff? ;-)

**Comment by darktrojan** [comment]
The lock/unlock button is in 83 (just released) and the number of rows/columns will be in the 84b3 (next beta). I'm closing this now to tidy up the open issues list. Thanks for your input @randomname42.
