### ISSUE TITLE
Tile opening behavior and new tab page address not working as before

### ISSUE THREAD

**Issue by zitronenbaum** [darktrojan/newtabtools#289]
After the most recent update (currently using version 82.2 on Firefox 55.0.3), two things have changed in an undesirable way:

1) Clicking on a tile now opens that link in a new tab, and the new tab page stays open as another tab in the background. I found the previous behaviour, where the new tab page would get overwritten with the tile clicked on, much more useful.

2) This is only a minor aesthetic issue, but the address bar, rather than the greyed out and cursive "Enter a search or address" or similar that used to be there before, now displays the path to the xhtml page:
![newtab](https://user-images.githubusercontent.com/13196860/29929376-a7c68074-8e6b-11e7-9c7c-db3612ea80de.PNG)

The rest is working very well. Thanks for the time and effort spent on developing this great add-on!

**Comment by darktrojan** [comment]
1. That's not normal. Works as expected for most. I guess you have a setting that behaves differently because it's now a moz-extension: page instead of an about: page. I can't think of such a setting though.

2. See #274.

**Comment by GridCube** [comment]
I'm having this same issue and it breaks my workflow so much I've had to revert to the default newpage, else if you start typing after a new page is open, you just add text to an url and not a new search or address

**Comment by darktrojan** [comment]
@zitronenbaum Did you solve this? Please close the issue if you did.
