### ISSUE TITLE
Preferences Button

### ISSUE THREAD

**Issue by Regdop** [darktrojan/newtabtools#290]
All the preferences button allows me to do is "Show Top Sites", "Show blank Page", or "Learn about new Tab"...It does not give me an option to edit my tabs...please advise.  Happy to contribute to a working application!
![screen shot 2017-09-01 at 11 18 11](https://user-images.githubusercontent.com/31525939/29951632-47fa5e44-8f07-11e7-9b0d-e207188f944a.png)

**Comment by darktrojan** [comment]
See #280.

**Comment by Regdop** [comment]
Hi,…That doesn’t help because i use a Mac?
cheers
Gary
