### ISSUE TITLE
Question: Move from FireFox

### ISSUE THREAD

**Issue by DontPlayTheGame** [darktrojan/newtabtools#292]
This is only a question:

Do you think, you could move away from FireFox with NTT to a webkit based browser like Brave etc.?
I don't know if it is needed to make any extension request for doing so (https://community.brave.com/c/feature-requests/extension-requests) 

FireFox is broken and i don't care anymore about FF. NTT is not the only thing which is now not really usable with the changes in FF. And if Mozilla do not care about me as a user why should i care about Mozilla? (see: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1322304  9 months old and in fact nothing is done) 

PS: just for other users: Version 81 still works as "we" expect.

PS.PS: is just made a request: https://community.brave.com/t/extension-new-tab-tools/6994

**Comment by darktrojan** [comment]
Very unlikely. I don't know much about the extension environment on Brave but I suspect it can do even less of what New Tab Tools needs than WebExtensions.
