### ISSUE TITLE
Launcher Question

### ISSUE THREAD

**Issue by Boojii** [darktrojan/newtabtools#293]
I was wondering if the launcher is ever coming back, I miss that the most from the previous version.
I understand with firefox's latest sweeping changes that you have a lot more important things on your plate, and I may be in minority of users who used the launcher, but it was a handy thing to have.

I was just curious if the launcher is gone for good?

**Comment by darktrojan** [comment]
At the moment the answer is yes, it is gone for good. I think there is some discussion about giving extensions permissions to do what it did, but that's as far as I know. I can't see it happening soon.

**Comment by Boojii** [comment]
That's a shame, but thank you for your hard work.
