### ISSUE TITLE
Low-res thumb-nail scaling redux: Retina/HiDPI

### ISSUE THREAD

**Issue by okdana** [darktrojan/newtabtools#294]
Hey again! Follow-up to #282: I re-applied my custom thumb-nails on my non-Retina computer at work and i think your changes have more-or-less addressed the issue i was having. The scaling method doesn't seem as crisp as before (pre-WebExtensions), but i can deal with that. Thanks!

I don't think the change is effective on Retina/HiDPI displays, however. The scaling method appears to use the tile size in device-independent pixels, which produces very low-resolution images on Retina devices. In fact, if i look at the thumb-nail blobs in the inspector, it seems that the images on my Retina device are actually *smaller* (in 'real' pixels) than the ones on my non-Retina one.

I'm thinking this can be addressed by just multiplying the image size you're getting now by `window.devicePixelRatio`, right?

ETA: 56.0b5 + 84.0b2, if that wasn't clear

**Comment by darktrojan** [comment]
Custom thumbnails should have at least twice as many pixels in each direction as the first tile. [See here](https://github.com/darktrojan/newtabtools/blob/VERSION_84B2/webextension/newTab.js#L221) and [here](https://github.com/darktrojan/newtabtools/blob/VERSION_84B2/webextension/fx-newTab.js#L440). This is the same behaviour as before, unless it's broken (works for me).

What is your device pixel ratio? I was under the impression that no desktop device had greater than 2 but I could be wrong. Also, what is the result of typing `Prefs.thumbnailSize` in the developer tools console? Does it seem right (twice the largest dimension of a tile)?

**Comment by okdana** [comment]
Actually, your comment led me to the realisation that the thumb-nail size value is set based on the largest tile dimension *given the current window size*, which is of course variable. I guess that didn't occur to me before. My browser window was apparently smaller when i set the thumb-nails than it is now, so it's having to blow them up.

If i maximise the window, re-apply the images, and then un-maximise again, things are noticeably better.

However, `Prefs.thumbnailSize` is in fact equal to 2x the largest tile dimensions in DIP, which is only 1x the largest tile dimension in real pixels. In other words, for example:

* Largest tile dimension in DIP: ~245
* Largest tile dimension in real pixels: 490
* Largest image dimension in real pixels: 490

I don't *think* that is appropriate for a Retina device, is it? It seems like it should be 2x real pixels (4x DIP), because otherwise there is no 'slack' like there is on a non-Retina device.

My device pixel ratio is `2`, btw.

**Comment by darktrojan** [comment]
Yeah well, the only reason there is slack is because Firefox's image downscaling is so bad. I've never taken pixel density into account. Maybe I should …

**Comment by okdana** [comment]
Yeah, it doesn't seem incredible. I think the maximise-before-applying trick should be good enough to address my immediate problem, though, so i suppose i defer to your judgement on the density thing. 🤷‍♀️
