### ISSUE TITLE
Address bar shows a long moz-extension URL

### ISSUE THREAD

**Issue by kecugks** [darktrojan/newtabtools#295]
Like a lot of users, I also use the address bar for searching (in fact I have the search bar disabled since I don't use it anymore). With the in-built New Tab page (regardless of settings), my searching routine would be like so:

1. Click on the **+** button or Ctrl+T to open a new tab;
2. New tab opens and typing cursor jumps into the address bar;
3. I can then directly type the search query or the address into the bar.

This is possible because with the built-in New Tab, instead of saying "about:newtab", the address bar actually says _Search or enter address_ in a light grey colour which allows typing directly.

Now, your add-on is perfect for me, I just have one problem with it: upon opening new tabs, the address bar says "moz-extension://cf740309-a13d-44bc-9f43-b281314c524a/newTab.xhtml" and doesn't allow typing directly, but the typing cursor still jumps into it!

Do you think it would be possible to hide this long ugly address and mimic built-in New Tab behaviour?

**Comment by darktrojan** [comment]
Not possible. Sorry. See #274.
