### ISSUE TITLE
Feedback wanted: Option to limit history tile instances of a site

### ISSUE THREAD

**Issue by scorpion451** [darktrojan/newtabtools#296]
Is there still an option to limit the number of history tiles filled from particular sites?
I found it extremely useful, so if it's been removed it would be nice to have it brought back. 
If it's still available, where do I find it now?

**Comment by darktrojan** [comment]
It's gone but will be coming back soon, because this really annoys me too.

**Comment by darktrojan** [comment]
I've just released a new beta version containing this feature, and I would like feedback on it, so I'm borrowing this issue to ask for it.

**Comment by olloff** [comment]
Awesome feature!   
Speaking about UX, now if number of unpinned tabs switched to _unlimited_, it can be altered to 0 (I believe this means no unpinned tabs) by pressing "+", which is confusing.
Can it be tweaked to _press "-" to set no unpinned tabs_ and _press "+" to actually set a number of unpinned tabs_?

**Comment by artworksmetal** [comment]
FYI - this is looking a bit strange.  FF 56.0 and NTT 84. 
![ntt](https://user-images.githubusercontent.com/31712900/31312259-4a3545e2-ab8c-11e7-9195-36586f0b718f.jpg)

**Comment by darktrojan** [comment]
@artworksmetal Oh fun! :-) I can fix that.

**Comment by artworksmetal** [comment]
It just occurred to me that the purpose of this is to prevent duplicates to the pinned tiles (duh!) .
 I suggest that 0 would be the more useful default, assuming that multiple pins from a domain would be the exception. 
I recognize of course that I may use NTT differently than others.
