### ISSUE TITLE
New Tab Tools consumes lots of CPU

### ISSUE THREAD

**Issue by hooloovoo79** [darktrojan/newtabtools#297]
I noticed that NTT was consuming a lot of CPU in my main profile, so I made a brand new profile and installed NTT. Whenever I opened a new tab, NTT caused more than 60% utilization of a single core of my CPU. When that tab with NTT was closed, usage returned to normal.
Let me know if you want me to do anything to help you with this.

**Comment by darktrojan** [comment]
What version of NTT do you have? I've seen another report that said this happened in one version but not another.

**Comment by darktrojan** [comment]
Never mind, found it!
