### ISSUE TITLE
Newtab tools not work after update firefox

### ISSUE THREAD

**Issue by Mechel** [darktrojan/newtabtools#298]
Newtab tools not work after update  firefoxportable to 55.0.3 and when choose option "Never remember history".

**Comment by yuhler** [comment]
I had the same issue here. Grrrr. I was running FF 52.0.2 on my Win 7 64-bit laptop. Other extensions broke as well: Mozilla Archive Format, uBlock Origin, and uMatrix. Some of these extensions started working again after a FF downgrade back to v52.0.2 but uBlock start working when I was about to make a full FF uninstall/re-install. Alas, NewTab Tools still jammed.
I have a WinXP tower with the same setup and there both FF 52.0.2 and extensions are working nicely.

**Comment by thc133** [comment]
Same for me with FF 55.0.3 (32bit) on Win 8.1.

**Comment by darktrojan** [comment]
Please read #280.
