### ISSUE TITLE
Something changed last week

### ISSUE THREAD

**Issue by khitron** [darktrojan/newtabtools#299]
Hi. Something wrong changed last week,
A part of preferences disappeared, for example an ability to refresh the thumbnail.
Or When opening new tab, there is an address of it in browser address filed,
"moz-extension://ed04c5f7-3067-485a-8b9e-205105e24ac2/newTab.xhtml".
Thank you.

**Comment by Lonelydad** [comment]
I agree. I had a tab page with over a dozen stored tabs on it. Now all they show is an empty box. No option shows up to allow me to edit a tab. The pin icon can be toggled on and off, but the delete tab 'X' doesn't work. And the URL box has the above string in it and doesn't clear.

**Comment by MrChris123** [comment]
Filter open issues with "moz-extension" to see further information.

**Comment by khitron** [comment]
Thank you, @MrChris123, I did these, and it's much worse.

**Comment by darktrojan** [comment]
> A part of preferences disappeared, for example an ability to refresh the thumbnail.

Yes, it has gone. With Firefox's new extension system, I cannot do that any more.

> When opening new tab, there is an address of it in browser address filed,

Yes there is. I cannot do anything about it.

@Lonelydad please start your own issue and post a screenshot, I don't think I've seen a report like that before.

**Comment by khitron** [comment]
And what about me? Thank you.

**Comment by darktrojan** [comment]
@khitron My previous reply was to you. That's your original comment I'm quoting. :-)

**Comment by khitron** [comment]
Sure, but there were just a part of the problems. Thank you.

**Comment by darktrojan** [comment]
What other problems are you having?

**Comment by khitron** [comment]
That's the problem it's not stable. Different problems appear and disappear every day. For example, from time to time one ,ore thumb is replaced with gray square, and I can't restore it. And much more. Thank you.

**Comment by darktrojan** [comment]
That sounds like the sort of thing I was experiencing in 82 that caused me to make my own thumbnails in 83. Before that I used Firefox's thumbnail generator that likes to not generate thumbnails for some sites for non-obvious reasons. What version are you using?

**Comment by khitron** [comment]
As i said, it's just a symptom. The last one. 55.0.3. Thank you.

**Comment by khitron** [comment]
Sorry?

**Comment by khitron** [comment]
Hello. Are there some news about the bug? Thank you.

**Comment by darktrojan** [comment]
I still have no idea what you actually want, so no. Please try using the latest version of Firefox and the latest version of New Tab Tools, and if you have a specific problem, please open another issue.
