### ISSUE TITLE
new tab doesn't work with firefox v55.0.3? workaround

### ISSUE THREAD

**Issue by ugoboccini** [darktrojan/newtabtools#300]
Hi,have found this workaround

After upgrade of fire newtab tools doen't work anymore.
After some tries I found this workaround

Install New Tab Override exstension, open a new page.
uninstall New Tab Override extension , turn off Firefox.
Open Firefox, open a ne tab page et voilà until the great developper won't make a compatibility version!!

Bye

**Comment by MrChris123** [comment]
> until the great developper won't make a compatibility version!!

Nice attitude.

1. Do you understand that it is Firefox framework changes that have effectively broken a whole heap of add-ons?
2. Have you ever contributed any money to darktrojan for NTT, or do you just imagine the shoemaker's elves do the development in the night when no one is watching?

**Comment by darktrojan** [comment]
@MrChris123 Thanks for helping with the avalanche of new issues, but I'm not sure OP has the bad attitude you suggest.

@ugoboccini Interesting if that works, but from what I've seen in the last week I don't think it's doing what you think it's doing.

**Comment by RedSpot5** [comment]
Workaround, though not pretty and may or may not work on the first page opened (just press the 'home' button).
I do not know how I got there, but adding the following bit as homepage and make new tabs open the homepage makes this great add-on keep on working.

code:
moz-extension://[large number, probably sensitive so removed]/newTab.xhtml

![fire](https://user-images.githubusercontent.com/31684297/30097021-bb2c223a-92db-11e7-9d4f-fd1ef3707a98.jpg)

**Comment by rugk** [comment]
The numbers are not sensitive (just add-on ID or so). And `moz-extension://ee2cc4cb-681d-42fc-bc57-8780befbb9ee/newTab.xhtml` is the URL. It cannot load images and so on.

https://github.com/darktrojan/newtabtools/issues/280
