### ISSUE TITLE
All tabs lost on Firefox 53.0.3 (32 bit) on Win x64 and NTT 83.0

### ISSUE THREAD

**Issue by MrChris123** [darktrojan/newtabtools#301]
@darktrojan - As mentioned in https://github.com/darktrojan/newtabtools/issues/283#issuecomment-327321829 since Firefox update I have lost all my tiles on the NTT new tab page. All that appears a list of recently closed tabs across the top of the page. 

Other information:
1. As mentioned by others, the URL of this page is now moz-extension://<some guid>/newTab.xhtml
2. I uninstalled and reinstalled NTT as suggested in https://github.com/darktrojan/newtabtools/issues/280 but there is no change.
3. As mentioned in https://github.com/darktrojan/newtabtools/issues/283#issuecomment-327321829 the contents of my `[your profile folder]/browser-extension-data/newtabtools@darktrojan.net/storage.js` are `{"version":83,"versionLastUpdate":"2017-09-04T10:42:15.624Z"}`
4. Following your suggestion I looked at https://github.com/darktrojan/newtabtools/issues/281 but there was no `newTabTools (default)` entry in the **IndexedDB** storage section in developer tools.

Thanks for your time,

Chris

**Comment by kghbln** [comment]
Same here. I am on Firefox 55.0.2 (64-Bit) for Linux Mint Sonya (18.2). I had to deacivate. :( This is a cheerful encouragement for a fix.

**Comment by darktrojan** [comment]
@MrChris123 This is weird. It looks like IndexedDB is not working, could something have set `dom.indexedDB.enabled` to false?

**Comment by MrChris123** [comment]
Just checked and it is still defaulted to true.

**Comment by darktrojan** [comment]
Do you have any of the same add-ons as [this user](https://github.com/darktrojan/newtabtools/issues/307#issuecomment-328676915)?

**Comment by MrChris123** [comment]
I have "ColorZilla", "Cookie Whitelist, With Buttons", "cssUpdater", "FireFTP", "New Tab Tools", "Print/Print Preview", "Tab Groups", "Web Developer", "Wiktionary and Google Translate", "XSL Results", "You Tube Dark Theme", "YSlow", "FiddlerHook" (disabled) and "Fire IE" (disabled).

So we have Tab Groups in common.

**Comment by darktrojan** [comment]
Okay. I really doubt it's an extension then. I'm going to close this issue, because it seems to be the same problem as #307 and I feel like I'm repeating myself. There are some more things you can try there. (Hopefully something in my most recent comment works for both of you.)
