### ISSUE TITLE
Preferences not saved?

### ISSUE THREAD

**Issue by bryce-lynch** [darktrojan/newtabtools#302]
I'd like to keep the new "titles from browsing history" and "recently closed tabs" options disabled. However, they seem to re-enable randomly (I have to go to preferences and disable them at least once every day).

I'm using NTT 83.0 with Firefox 55.0.3 64-bit on Linux.

**Comment by darktrojan** [comment]
Thats … _interesting_. I can't think of any reason this would happen, unless all the other prefs are already set to the default and something is resetting all of them.

**Comment by bryce-lynch** [comment]
Actually I've been experiencing issues with a few other extensions too since Mozilla started moving to webext, so perhaps it's a glitch that will get sorted out reinstalling Firefox and using the new webext addons instead of the legacy ones... I'm going to do this when FF 57 comes out and hopefully close this issue.
