### ISSUE TITLE
all New Tab pages are missing when reloading a session

### ISSUE THREAD

**Issue by randomname42** [darktrojan/newtabtools#303]
This is odd. Since the webkit update I have noticed that any New Tab pages I had open will not exist when I reopen Firefox, every time. This never happened before the webkit update.

I'm guessing it has something to do with the weird address that New Tab Tools is forced to use after the switch over to webkit?

More information: I have all tabs/windows from last time automatically reload when starting Firefox. I forget if that's built into Firefox or not. I do use Session Manager, which automatically backs up the current session in case of a crash.

Some tests: I tried disabling New Tab Tools, loading some default Firefox new tab pages, and restarting Firefox. Those stay when reloading the session, even after enabling NTT again and restarting. But all NTT's new tab pages always disappear when reloading a session. It's really strange behavior.

**Comment by darktrojan** [comment]
(You mean WebExtensions. Webkit is something different entirely.)

This is somewhat expected. Firefox closes all pages the add-on has open when the add-on shuts down, which it does when Firefox shuts down.
