### ISSUE TITLE
Tabs on New Tab Page no longer have a right-click 'edit tab' function.

### ISSUE THREAD

**Issue by DonQuixoteIII** [darktrojan/newtabtools#305]
Per title, can no longer go into a tab to change some settings or 'force' an image page.

**Comment by darktrojan** [comment]
I really wish I could bring this back, but so far the options I've tried are unsatisfactory.

**Comment by darktrojan** [comment]
Scratch that, I just tried something I knew about but never tried before. This might get fixed after all! :-)

**Comment by DonQuixoteIII** [comment]
Rats.  D***ed FF....

Scratch that, I'll patiently wait.
