### ISSUE TITLE
For whatever reason 'New Tabs Tools' keeps getting 'un-installed'

### ISSUE THREAD

**Issue by DonQuixoteIII** [darktrojan/newtabtools#306]
One minute I have 'New Tab Tools' next minute, maybe not.  When checking addons, nothing seems amiss, but the only way to get 'New Tab Tools' working again is to re-install it.

**Comment by darktrojan** [comment]
Uninstalled, or just stops working? If you've just updated for the first time in a while, you should read #280.

**Comment by DonQuixoteIII** [comment]
It is very like some of the screens on that thread.  Don't know if I can add much, but for me it has happened between new tabs.  It is immediately noticeable because in NTT, the tiles are very squared off, while FF's tabs are rounded corners.  That, and your blurb is not on the bottom of the page and also the settings 'gear' is missing.  I have had it occur twice since the update to FF 55.
