### ISSUE TITLE
Recently closed tabs instead of new tabs

### ISSUE THREAD

**Issue by Winter84** [darktrojan/newtabtools#307]
When I open a new tab with NTT 83.0 I get a blank page with a line across the top listing a few Recently closed tabs. Here is a screenshot. I am running Firefox 55.0.3 under OS X 10.10.5. My apologies if this is behaviour that has already been reported.

I have tried the suggested fix of restarting Firefox with NTT uninstalled.
![screen shot ntt problem](https://user-images.githubusercontent.com/31829138/30252529-e67a3dc6-966b-11e7-808d-313257ad14aa.png)

**Comment by darktrojan** [comment]
As I said on another issue, it looks like IndexedDB is not working, could something have set `dom.indexedDB.enabled` to false?

**Comment by Winter84** [comment]
I had already checked that. It is set to its default of true.

**Comment by darktrojan** [comment]
Huh. Have you got these entries in the developer tools?

![devtools](https://user-images.githubusercontent.com/1540303/29822191-b7bf977a-8d1e-11e7-98a6-14ffd9700467.png)

**Comment by Winter84** [comment]
No, I don't. Here is a screen shot.
![screen shot ntt problem 2](https://user-images.githubusercontent.com/31829138/30299664-90b24fea-9748-11e7-8378-bd6001f9dbc7.png)
 
My other enabled extensions are: Adblock Plus, Cookie Monster, DuckDuckGo Plus, Go Parent Folder, KeeFox, NoScript, OneTab, PrintEdit, QuickDrag, Show Parent Folder, Tab Counter and Tab Groups.

**Comment by darktrojan** [comment]
Hmm. I suspect Cookie Monster, but the author has removed it from AMO so I can't check it out.

**Comment by Winter84** [comment]
Disabling Cookie Monster doesn't help, I'm afraid. Sorry to be so challenging. I hope this is helpful.

**Comment by darktrojan** [comment]
It's not your fault that Firefox is broken (unless it is)!

What happens when you put this code in the console (with a new tab page open)? I don't hold much hope as the most useful thing I've got is "UnknownError", but something helpful *could* happen.

```javascript
try {
	var request = indexedDB.open('thisIsATest', 1);
	request.onsuccess = console.log;
	request.onerror = console.error;
	request.onupgradeneeded = console.log;
} catch(ex) {
	console.error(ex);
}
```

**Comment by Winter84** [comment]
It just gives "undefined". Is that informative?

![screen shot 2017-09-12 at 02 12 29](https://user-images.githubusercontent.com/31829138/30303470-3fd76a98-9760-11e7-8c7d-e969bc96fdc8.png)

**Comment by darktrojan** [comment]
It was unexpected, so I guess that's informative. That code should either succeed and log a success message, or fail and log a failure message. It doesn't do either. Try this:

```javascript
try {
	var request = indexedDB.open('thisIsATest', 1);
	request.onsuccess = console.log;
	request.onerror = console.error;
	request.onblocked = console.error;
	request.onupgradeneeded = console.log;
	'finished';
} catch(ex) {
	console.error(ex);
}
```

I have no idea what's going to happen. I know what *should* happen, but I reckon you'll get `undefined` again.

**Comment by Winter84** [comment]
Yes: `undefined`, again.

**Comment by darktrojan** [comment]
Okay, this is screwed up and it's starting to really bug me now. I took that last test we did to one of the Firefox developers mailing lists and even there people were stumped at how that result could happen.

It did give me a few ideas though. In your profile folder (go to `about:profiles` and you can open it from there), under `storage/default`, is there a folder named `moz-extension+++[the letters and numbers from your address bar]`? If there is could you make a .zip file of it and email it to me (geoff at [my GitHub user name] dot net). Then delete the folder, restart Firefox and see if New Tab Tools is still busted.

Failing that, use about:profiles to create a new profile, install New Tab Tools and see what happens.

**Comment by MrChris123** [comment]
In https://github.com/darktrojan/newtabtools/issues/301#issuecomment-329099932 you suggest I come over here, so here I am.

Just to conform I too get `undefined` for both scripts, but both of them also give

```
DOMException [SecurityError: "The operation is insecure."
code: 18
nsresult: 0x80530012
location: debugger eval code:2] 
```

**Comment by Winter84** [comment]
I have created a new profile and installed NTT but no other add ons. NTT sort of works: spaces for the images, but no images. Please see the screen shot attached.
![screen shot 2017-09-13 at 22 55 56](https://user-images.githubusercontent.com/31829138/30402995-8b5647aa-98d7-11e7-80e5-999cf8b90caf.png)

**Comment by darktrojan** [comment]
@MrChris123 Hmm, that's interesting. I wonder what causes that.

@Winter84 Hooray, progress! The lack of images is expected, thumbnails are only created if a page is high enough on the list to be on the new tab page (or the next 10) before you visit it. Oh, and also addons.mozilla.org tiles never get a thumbnail, some security feature I think. I didn't find anything in your email that would explain the bug, so I'm afraid I still don't understand it.

Looks like creating a new profile solves the problem, so I suggest using the Refresh Firefox feature to copy your stuff to a new profile.

**Comment by MrChris123** [comment]
@darktrojan The scripts error if cookies are disabled. If I enable cookies and ran the second script I get 

```
"finished"
success { target: IDBOpenDBRequest, isTrusted: true, currentTarget: IDBOpenDBRequest, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, composed: false, timeStamp: 5103.006683754239, cancelBubble: false, originalTarget: IDBOpenDBRequest }
```

**Comment by darktrojan** [comment]
Okay! Problem solved. Nice work @MrChris123.

If you want to keep cookies disabled you can create an exception.

**Comment by MrChris123** [comment]
@darktrojan I have added an exception for the moz-extension URL. There are no tiles showing up still though. Is it likely that this issue has wiped my cache of NTT sites?

**Comment by darktrojan** [comment]
Shouldn't have, and the prefs from old-school NTT will still be there. Are you seeing exactly the same thing as before? Have you restarted Firefox since adding the exception?

**Comment by MrChris123** [comment]
@darktrojan Restarted and NTT now showed my 35 tiles with correct text, but blank images. A second NTT showed 3 of the 35 tiles with images. Clicking on the tiles seems to create a new tile image. Don't know if there is any other way of generating them. 

Thanks for your help.

**Comment by Winter84** [comment]
Setting the cookie exception works for me as well, even while using Cookie Monster. Also images have started appearing for HTTPS pages as well, though this is happening on the Firefox new tab page as well, so presumably it is just a delayed effect of the latest Firefox version.

**Comment by darktrojan** [comment]
Nice, looks like this is solved. The pictures will show up as you visit pages – NTT has a new thumbnail system which starts without any thumbnails.

Thanks for your patience everybody!
