### ISSUE TITLE
Row of buttons missing (options, add-ons, bookmarks, sync etc.)

### ISSUE THREAD

**Issue by irenru** [darktrojan/newtabtools#308]
Hi darktrojan,
the problem is on the screenshot, there's no additional buttons anymore :(

When - recently, probably after some update. At the same time when all the thumbnails were gone.
Version of FF and NTT - latest.
Reproducible - yes, every time.
Classic Theme Restorer removed, didn't help.

![row-gone](https://user-images.githubusercontent.com/31849737/30272572-8b6df8de-970e-11e7-9a7b-146cfb06950a.jpg)

**Comment by darktrojan** [comment]
Indeed. With Firefox imposing this new extension system, the buttons no longer work. Sorry but I can't do anything about it.

**Comment by irenru** [comment]
Shoot. Anyway, thank you for such a great add-on! With many extensions closing now, it's cool to know that you're not giving up. Cheers from Russia :)
