### ISSUE TITLE
Firefox default tabs page returns after restarting Firefox

### ISSUE THREAD

**Issue by mclindgren** [darktrojan/newtabtools#309]
Hi,

I'm synchronizing my addons between all my computers. 

On my workstation at home, Firefox (version 55.0.3) it reverts back to the default firefox tab page after the browser is restarted. I have the same version of Firefox at work and on my laptop etc with the same plugins activated and it works on 2 out of 3 computers.

If I reinstall the plugin, it works until I restart the browser and open a new tab. Then the page "flickers" for a "milisecond" as if it reloaded the page, and the default Firefox tab page shows instead as if it was quickly reverted back.

**Comment by darktrojan** [comment]
It sounds a lot like the problems I've described in #280. There's something you can try at the bottom of the first comment which seems to work for a lot of people.

**Comment by mclindgren** [comment]
I can confirm that the solution described in #280 solved the issue, many thanks.
