### ISSUE TITLE
Summary of all the problems caused by the WebExtension update

### ISSUE THREAD

**Issue by darktrojan** [darktrojan/newtabtools#312]
This is a quick round-up of the major problems triggered by New Tab Tools becoming a WebExtension and what to do about them.

### My address bar is filled with all these letters and numbers
**Cause:** Firefox is stupid.
**Solution:** Wait for Firefox 57.

### I get the Firefox new tab page when opening a new tab
**Cause:** Firefox stuffed up the upgrade.
**Solution:** Run Firefox from the command prompt with the `--purgecaches` flag.

### I get the Firefox new tab page when going to my home page (it was New Tab Tools)
**Cause:** The new tab page moved to the address with the letters and numbers.
**Solution:** Change your home page to the address with the letters and numbers. The easiest way to do this is drag the address from the address bar to the home button.

### I get the New Tab Tools page, but there's no tiles
**Cause:** Cookies are disabled. New Tab Tools doesn't use cookies, but disabling them also disables something it does use.
**Solution:** Add a cookies exception for the new tab page address. Also check `dom.indexedDB.enabled` is set to true in `about:config`. Restart Firefox.

### New Tab Tools didn't copy my settings from the old version properly
**Cause:** Either (1) I am an idiot and stuffed it up, or (2) you skipped versions 82 and 83 and went straight to version 84.
**Solution:** (1) Can't be helped. I'm still an idiot. This has been fixed in v82.2 and you can read about it in #281. (2) Go back to v83 and follow the steps in #281. Should work.

### I can't drag bookmarks or other things on to the new tab page.
**Cause:** Firefox is stupid.
**Solution:** None. You can still add pages through the options pane. I know it sucks but I'm working on improvements.

### Things are missing, like the import/export feature or the buttons for downloads/addons/options etc.
**Cause:** WebExtensions can't do that.
**Solution:** None.

**Comment by darktrojan** [comment]
If you have a problem that's not covered here, and there's no issue already about it, please start your own issue, don't comment here.

**Comment by charlesbevans** [comment]
Not getting tiles any more and I did try to allow cookies on the tab page (moz-extension://4c28072b-abe7-ab4d-8b9d-10ba1b821df2/newTab.xhtml)

**Comment by darktrojan** [comment]
What about IndexedDB, could it be disabled? Check `dom.indexedDB.enabled` in `about:config`.

**Comment by charlesbevans** [comment]
Disabled it and no change. Looking at other issues, I should mention that I've been slow to update FF because I rely on addons that won't make the transition, so I may have skipped a version of NTT somewhere.

**Comment by Alukah** [comment]
Is NTT 81 no longer supported? I'm having this issue in Firefox 56

> I get the New Tab Tools page, but there's no tiles

Cookies are enabled and dom.indexedDB.enabled is set to true in about:config, but I still can't see tiles.

**Comment by charlesbevans** [comment]
I did a full refresh and it fixed itself, except sometimes it lets new windows open.

**Comment by Alukah** [comment]
Welp now the tiles are disappearing every time I close the browser, I have to do the whole disable -> restart -> enable whenever i open it again. I guess I'll stop using NTT until FF 57

**Comment by joeblowma** [comment]
> You can still add pages through the options pane.
Replacing a tile I had pinned before, I can only get this to work around 1 in 8 times... and then as soon as I hit the pin to pin it, it reverts to whatever random page was there before I edited the tile. Google FireFox is really letting me down.
