### ISSUE TITLE
add ties doesn't work

### ISSUE THREAD

**Issue by ugoboccini** [darktrojan/newtabtools#318]
Hi,
I have the follow problem with version 84,1.
I'm not able to add a new tile in firefox.
Only way found is to add a tile by options page.

thanks

**Comment by Maverynthia** [comment]
I have/had the same problem. I'm using Waterfox 55.2

**Comment by darktrojan** [comment]
The only way to add a tile is to use the options. Firefox broke all the other ways.

**Comment by Maverynthia** [comment]
I downgraded it and are using it on Waterfox then. I'll just set it to not update. :/ :\
