### ISSUE TITLE
Re: New Tab Tools couldn't start properly

### ISSUE THREAD

**Issue by okdana** [darktrojan/newtabtools#319]
Hey again. I'm getting this error in Firefox 56.0.1 with NTT 84.1. 

I saw #312 and #316, but none of the things you mentioned seem to apply to me:

* I'm not using Private Browsing
* I have history enabled
* I have cookies enabled
* I have IndexedDB enabled
* I tried adding a cookie exception anyway
* I tried starting the browser with `--purgecaches`
* I tried completely uninstalling and re-installing the extension

I was actually using NTT with the Firefox 56 beta and it worked perfectly fine, but i had to finally restart the browser and of course it upgraded me to 57, so i went back to the stable channel. Can't imagine what they would have changed between 56 beta and 56 stable to cause this.

Out of curiosity, i also tried NTT in Waterfox, which is based on Firefox 55. I get the same problem there.

Do you have any other ideas as to what it might be stuck on?

**Comment by DanaMW** [comment]
Hi there, Glad one of us is ok :)  When you say  not starting properly do you mind if i ask what exactly  you mean? what is it doing? If your cool with me sticking my nose in here.

**Comment by okdana** [comment]
I am cool with it — it's doing this:

<img width="1067" alt="screen shot 2017-10-15 at 02 32 04" src="https://user-images.githubusercontent.com/122095/31582730-22df1f5c-b151-11e7-985c-d087549b1d9c.png">

**Comment by DanaMW** [comment]
I ask because sometimes on startup of firefox mine just comes up to a blank page if NTT was the last page. But i am pretty sure it is  a firefox thing because if i leave my news reader as the last page  it comes up with the   the settings wrong until I refresh also.

**Comment by DanaMW** [comment]
Yours I think is  an error in the default newtab page,,, grid.js here some info i am reading now ..
https://searchcode.com/codesearch/view/26701953/

**Comment by darktrojan** [comment]
@DanaMW Your issue I can answer. Firefox can't always open the extension's page when it first starts up because the extension isn't ready yet. This is also a problem when New Tab Tools is the home page. There's nothing you can do about it, although there's a chance I'll be able to fix it in future.

**Comment by DanaMW** [comment]
cool thank you.

**Comment by darktrojan** [comment]
@okdana Your best option might be to start a new profile (which is a sucky option, I admit) and copy your stuff across. Sometimes things just get broken, especially if you're moving around between versions.

If you find something you think might be the cause, I'd like to know.

**Comment by DanaMW** [comment]
I tried a clean  profile already i have  your  tool running ff and chrome on windows 10  and  both again on linux (arch) and its not an issue on chrome so far.

**Comment by DanaMW** [comment]
Hey nice Dana I was wondering how many tiles you have (or had) set up and if you tried clearing out all the  setting  for NTT that you had in there including removing the newtab-savedthumbs folder in your profile directory?  (assuming you use icons and not the url) Just a thought, trying to help is all. Maybe in my rambling you can pull out something you can  use.

**Comment by okdana** [comment]
I have 18 tiles. I did try playing with the database in my profile, but i couldn't get anything out of it. Firefox 57 must have tainted the extension ID or something, idk

I've already spent more time fucking with this than i would have done setting up a new profile, so i decided to just give up and do that as suggested. I guess it'll have to work. Closing for now, cheers
