### ISSUE TITLE
firefox-style newtab at start

### ISSUE THREAD

**Issue by paolouliana** [darktrojan/newtabtools#321]
I tried typing "moz-extension: //000229fd-d6e1-4e75-a89a-ab0630c4b8da/newTab.xhtml" as my home page but it does not work, however when I open a new tab i have new tab tool

first firefox started directly with new tab tool as initial page (with setting about: newtab)

can I do it now?

thanks

**Comment by darktrojan** [comment]
You can set it as your home page, but it doesn't always load. Sometimes Firefox appears before the extension is ready.

The easiest way to set it is to drag the address onto the home button, or go into settings and click 'use current page' in the home page section.

**Comment by paolouliana** [comment]
I used the method: 'use current page' in the home page section

it works! thank you
