### ISSUE TITLE
hideable page action button

### ISSUE THREAD

**Issue by hkrware** [darktrojan/newtabtools#324]
the button should be hideable for people who like clean toolbars (like me)

**Comment by darktrojan** [comment]
I have no control over where the button goes. All I do is make it available and Firefox puts it where it wants.

**Comment by hkrware** [comment]
maybe an option to disable it, then? is that possible?

**Comment by darktrojan** [comment]
In the next beta the button will be on the toolbar instead of the URL bar. At least you can hide it from there.
