### ISSUE TITLE
Your icon is invisible on a built-in Firefox dark theme.

### ISSUE THREAD

**Issue by AjvarXX** [darktrojan/newtabtools#331]
Literally invisible. Neds at least a white areal and slight modding

![invisible ntt icon on dark theme](https://user-images.githubusercontent.com/9568793/32610223-c226bf98-c56a-11e7-8372-741759ef3ebf.PNG)

**Comment by darktrojan** [comment]
I know.

You can only use one icon image and it happens to be the colour it is. What's really annoying is Firefox has a really good way to use the same icon file and have it change colour to match the rest of the toolbar icons, but *they've deliberately disabled it for extensions*. FFS.

**Comment by AjvarXX** [comment]
> but they've deliberately disabled it for extensions.
Ooooh, sneaky monopolist's move, that is! It seems as if Firefox' devs have their feeling hurt from other's changing their GUI.

**Comment by eberhardweber** [comment]
I've seen icon colour inversion done in the webextension [Neat Url](https://addons.mozilla.org/en-GB/firefox/addon/neat-url/). The developer has implemented it in the options. It's probably a colour inversion, like "filter: invert(1)", which would probably be better than nothing! 

The add-on [Stylus](https://addons.mozilla.org/en-GB/firefox/addon/styl-us/) also allows for preferred icon selection. Not sure how they have implemented it.

I think the next-best case scenario (after automatic icon colour inversion on the basis of the theme being used) is to allow the user to invert or change the icon.
