### ISSUE TITLE
NTT activates properly in new tabs but not in the first tab of new windows

### ISSUE THREAD

**Issue by eberhardweber** [darktrojan/newtabtools#337]
I just updated to FF57 with NTT (v85) and was pleasantly surprised that the newtab extension marker in the URL bar is working now and one does not have to clear the address bar any more, New Tab Tools opens with an empty URL bar line. I also did not have to add the NTT extension path to Options > General > Home Page for NTT to activate in new tabs.

However, whenever I open a new _window_ instead of a new _tab_, the Firefox built-in newtab page opens instead. As soon as this is closed, or a new tab is opened, NTT activates again. It would obviously be preferrable to have NTT open every time, in new windows as well.

Is there an elegant solution for this problem that I can do my behalf?

**Comment by darktrojan** [comment]
Set New Tab Tools as your home page.

**Comment by eberhardweber** [comment]
After trying to follow your recommendation, I realized I no longer know how to find out the proper extension URL in FF57 since it is no longer readily visible for copy-pasting (which is, obviously, a good thing). 

I ultimately came to the conclusion that the necessary path can be made available for use by clicking the "Use Current Pages" option under Options > General > Home Page while a NTT-provided tab is open in the window you have your Options page open in. That way, Firefox feeds the path to the homepage box. The URL bar still works like it should!

This might be good information to mention to users somewhere :) Apologies if I have simply failed to read the step-by-step somewhere.

**Comment by ActionScripted** [comment]
For anyone finding this (like me) from the future: you can set NTT as your home page by opening it (new tab) and dragging "Extension (New Tab Tool)" near the URL bar onto the home icon in your toolbar.

You'll be prompted to confirm setting NTT as your new home page and things should work from there.
