### ISSUE TITLE
How to open firefox with the new tab? 

### ISSUE THREAD

**Issue by waltdisneypixar** [darktrojan/newtabtools#342]
hi

i want to set new tab as homepage like i had with Super Star

**Comment by r2308145** [comment]
set newtab page as your homepage

**Comment by waltdisneypixar** [comment]
what i did was 
bookmark the speed dial page
then go to settings in firefox
and choose that bookmark
Done!!!!

**Comment by DARKB1KE** [comment]
Yeah you have to create a bookmark of the NewTabTools page first before it even lets you set it as the startup homepage.
