### ISSUE TITLE
newtabtool occupying address bar when set as home page

### ISSUE THREAD

**Issue by dpassos1993** [darktrojan/newtabtools#345]
When I set the newtabtools as my home page, when i first start firefox it occupies the address bar:

![homwpagebar](https://user-images.githubusercontent.com/33725673/32898189-9df70556-cace-11e7-965d-06129e81a17d.png)

When I open a new tab it cleans up, but it's a inconvenience if one uses the address bar to do searches.

I'm using the showed address as home page in the firefox settings, if I use the about:newtab, as I did in early versios of the extension and the browser, it does not show the extension anymore but the firefox default new tab. It doesn't happen in Chromium.

**Comment by darktrojan** [comment]
This is Firefox's fault. I agree it sucks, but there's nothing I can do about it.

**Comment by abhisekssp4025** [comment]
Well I kind of fixed this...
![ff1](https://user-images.githubusercontent.com/23081515/32995242-b8ef340c-cd97-11e7-9fb2-ef7ab567828d.png)

Just set your homepage as this URL
![ffsettings](https://user-images.githubusercontent.com/23081515/32995260-0be41ede-cd98-11e7-9c76-12678b7a08f9.png)

Obviously if you don't want to sacrifice your homepage then I don't have any other suggestions :)

**Comment by dpassos1993** [comment]
This is how I have set NTT as homepage in the first place.

**Comment by hockeymikey** [comment]
@darktrojan This is still an issue for me using the most updated version on Waterfox 56.  Any solution?  Worse case, a solution that uses legacy apis to patch it.
