### ISSUE TITLE
newtabtools as homepage / URL bar focus

### ISSUE THREAD

**Issue by dezo2** [darktrojan/newtabtools#355]
Thanks for this great addon. When I set newtabtools as homepage and restart Firefox 57, the URL address bar is not focused (in Chrome it is). After creating new tab it is focused - is this another bug/annoyance in FF 57 or is there some other way to force focus to URL bar after FF start?

Also is there a way to open links automatically in a new tab?

**Comment by darktrojan** [comment]
I can't fix this, it is Firefox's fault. Hopefully they will do something about it.

**Comment by dezo2** [comment]
I suspected that, thanks for reply.

**Comment by XedMada** [comment]
Is there an item in the firefox tracker related to this? I've searched around but couldn't find it.
