### ISSUE TITLE
Firefox 57 on Andoid

### ISSUE THREAD

**Issue by smndhm** [darktrojan/newtabtools#356]
Hello,

I saw it was possible to install your extension on Firefox on Android but I can't make it work.
It must be because of there own new tab solution.

Do you know if it is possible to pass by it an make it work on Android ?

**Comment by darktrojan** [comment]
It's not actually Android compatible. (It might work, I've never tried, but it's not intended to be compatible.) I think sometimes the add-ons website erroneously says that it is compatible.

Sorry about that!
