### ISSUE TITLE
New Tab Tools couldn't start properly

### ISSUE THREAD

**Issue by spip93** [darktrojan/newtabtools#362]
Hello everybody,

I'm using the last version of New Tab Tools (version 85) and me too, I saw #312, #316, #319 but none of the things you mentioned seem to apply to me. Mee too :

- I'm not using Private Browsing
- I have history enabled
- I have cookies enabled
- I have IndexedDB enabled
- I tried adding a cookie exception anyway**
- I tried starting the browser with --purgecaches
- I tried completely uninstalling and re-installing the extension

I even add that :

- I created another profile
- I disabled all other addons except New Tab Tools

But even that did not work.
I dry (as we say in French), I do not see what other solution.
I do not understand why; today I installed New Tab Tools on my work computer and it works properly.

And you ? Would you please an idea?
In advance, thank you for your answer.
Have a good day ;-)

** In this regard, New Tab Tools is one of the exceptions since on a new tab, when I click the i on the far left of the address bar, it tells me that it is part of the exceptions

**Comment by darktrojan** [comment]
Hmm, that's not good. I've never had it not work in a new profile before. Perhaps you should try removing and reinstalling Firefox. Also, I assume you're using Firefox 57, is that correct?

**Comment by mjbogusz** [comment]
I've experienced this just few minutes ago - and it was working fine just a bit earlier. I have no idea, what has changed - there have been no Firefox updates, no NTT updates (it seems I've been using 86b2)... Screenshot below.

![ntt_cantloada](https://user-images.githubusercontent.com/4386503/33408605-9b0b0eb0-d577-11e7-8557-92c3a07a3438.png)

Possibly worth noting: it did happen on a Win10 machine.

---
# Workaround
(worked for me, but __no guarantees__):
* go to `[your_firefox_prodile]\browser-extension-data\newtabtools@darktrojan.net\` and back-up `storage.js` or its contents
* uninstall NTT
* close Firefox
* manually purge the extension data (see step 1) and storage (`[profile]\storage\default\moz-extension+++[your_ntt_uuid]`)
* open Firefox, install fresh NTT
* close Firefox, restore `storage.js`
* open Firefox, let NTT redo the thumbnails

Warning: __this will change NTT's UUID and reinstall NTT on all synced machines!__

I've additionally restored the thumbnails using script from https://github.com/darktrojan/newtabtools/issues/287#issuecomment-346503502 , but I had them backed-up beforehand.

Before that reinstall workaround I've tried manually purging the extension data, storage etc but nothing worked.

**Comment by gendalv** [comment]
I'm not getting this message, sometimes it's just blanks page, so I have to click the home button to force it to go to NTT page.

**Comment by spip93** [comment]
Well, I ended up uninstalling Firefox 57, removing all the folders (in AppData \ local and Roaming) and reinstalling it later.
Fortunately, I have an account at Firefox Sync and suddenly, it has resynchronized and it gave me everything (bookmarks, passwords, ... and all extensions).
Go understand why, but now, New Tab Tools works !!
Thank you for your answers.
I hope my experience will help others, including those who are hesitant to completely uninstall Firefox for fear of losing their bookmarks etc ...
Have a nice day ;-)
