### ISSUE TITLE
Thumbnail files have no file extension

### ISSUE THREAD

**Issue by artworksmetal** [darktrojan/newtabtools#373]
Been away and looking forward to setting up NTT with the Backup / Restore option. Went to update some thumbnails (using the new toolbar feature) and had a hard time finding them. Browse didn't default to the correct location and a search revealed nothing. After a deep dive I found the image files have no extensions, so do not show in searches or in the file upload DB. Renaming is required for each one in order to see what it is before selecting it.
Verified this on 2 PCs with NTT 86 and FF 57.0.3
Cheers and Happy New Year.
![ntt](https://user-images.githubusercontent.com/31712900/34471449-269ccd60-ef18-11e7-97f4-2e5e0b7f7da0.jpg)

**Comment by darktrojan** [comment]
That's just how Firefox stores stuff like that. Nothing to do with NTT.

**Comment by artworksmetal** [comment]
Thanks, Obama! (I mean, Mozilla!)
