### ISSUE TITLE
Unable to make it available on start up

### ISSUE THREAD

**Issue by XOR-op** [darktrojan/newtabtools#378]
I can't make it available on start up page. I have tried about:blank (just a blank), about:newtab (default newtab but not this) and even moz-extension://f80a360e-8248-493f-9d3f-717b8bccc341/newTab.xhtml (the old version used to be). Is it unavailable in the latest version?

**Comment by artworksmetal** [comment]
If you want NTT to come up when you open Firefox, then do the following:
Open Firefox.
Click on a new tab (+ sign) twice to open NTT twice.
Close the original blank new tab page.
Go to the right hand NTT page and select Tools/Options from the menu.
You should now have 2 tabs open - NTT and the Options page.
Select "Show your home pages" and click on the "Use Current Pages" button.

Hope that works for you.

**Comment by GalayZloy** [comment]
I had the same problem, and this solution helped me.

**Comment by GalayZloy** [comment]
Now it is moz-extension://4942d729-1f50-4662-9106-eca24ed1138a/newTab.xhtml

**Comment by XORNOTXOR** [comment]
@artworksmetal Thank you for your tutorial. It does work now.

**Comment by artworksmetal** [comment]
Glad to help. I think this is an issue with Firefox. In the last week, I've had to do it twice. Some update or something? I don't know. But when it happens it also loses my pinned tabs.
