### ISSUE TITLE
Firefox ESR compatability?

### ISSUE THREAD

**Issue by Jorlem** [darktrojan/newtabtools#382]
The add on doesn't appear to work in the Firefox ESR release.  The initial problem is version numbering, as Firefox ESR is currently on version 52.6.0, so Firefox does not want to install the add on.  I got around this by opening up the xpi file and editing the minimum required Firefox version number, and it installed, but even then it does not appear to function.  Instead of the sixteen tab tiles I am used to with NTT, I only have fifteen, and a search bar on the top. Clicking the gear in the upper right just gives e a choice between showing my "top sites" or a blank page. I had been running Firefox 56, and switched to the ESR version after updating to 58 to see how it was. (I didn't like it, obviously.) I am on Windows 10.

I've tried both the most recent version of NTT on the FIrefox add-on page (86.2) and version 83.2, which if I understand correctly, is the last version that was not completely reliant on Firefox's new way of doing add-ons.

While I do have Classic Theme Restorer and Tab Mix Plus installed, I have never had issues with them conflicting in the past when I was on Firefox 56 and earlier, and disabling both of them did not fix the issue.

**Comment by darktrojan** [comment]
You want version 81.

**Comment by Jorlem** [comment]
Thanks, that worked.  Sorry to be a bother.
