### ISSUE TITLE
Broken on Nightly

### ISSUE THREAD

**Issue by hooloovoo79** [darktrojan/newtabtools#390]
New Tab Tools broke with something landed between the 2nd 2018-03-07 nightly and the 1st 2018-03-08 nightly.
Looking at the list of fixes posted in the daily build thread on mozillazine didn't have anything immediately jump out at me as the likely cause, so I don't really have a place for you to start looking.

**Comment by darktrojan** [comment]
Yes I know. Currently having an argument with a Firefox developer about whether they should fix what they broke.

**Comment by darktrojan** [comment]
I've released a temporary fix. Not really that happy about it, but whatever.

**Comment by stbeile** [comment]
New Tab Tools is also broken for me on 59.0.

**Comment by darktrojan** [comment]
@stbeile Firefox 59 is not affected by this particular bug.

**Comment by darktrojan** [comment]
Fixed now.
