### ISSUE TITLE
Other Firefox Extension Opening In Tabs

### ISSUE THREAD

**Issue by matt7c** [darktrojan/newtabtools#404]
I'm trying to add a non "http://..." link,its a Firefox extension that opens in a tab.
ntt isn't letting me add this. I'd like to be able to add e.g. **[moz-extension://ed33e8fd-73ee-8c49-9b75-9ce21f9002fe/manage/manage.html](moz-extension://ed33e8fd-73ee-8c49-9b75-9ce21f9002fe/manage/manage.html)**-Simple Tab Groups. It works as a bookmark, but I'd also like it in my NewTab Page.

**Comment by matt7c** [comment]
return /^(https?|ftp|moz-extension):\/\//.test(url) && new URL(url);

**Comment by darktrojan** [comment]
I'm surprised this works. You can't link to a file on your hard drive, but you *can* link to another extension? Weird.

Anyway, I've pulled the change from your fork. Note that you won't be able to get a thumbnail image for your tile.
