### ISSUE TITLE
Unpinned/removed tiles not being replaced new ones (v88 regression)

### ISSUE THREAD

**Issue by eberhardweber** [darktrojan/newtabtools#412]
After installing v88, I got a blank spot in my grid where a history-populated unpinned tile should have been. It's not being populated by a new tile, and now that I unpinned another pinned tile, its place is blank as well and not being repopulated from history.

Since v88 was a permission update, I thought I would reinstall v88 to be re-asked for permissions, but that had no effect on the issue either. Restarting the browser or disabling/enabling the add-on had no effect either.

This also means I cannot add new tiles. v87 was working fine for me.

**Comment by darktrojan** [comment]
Yeah, um … I screwed up. Accidentally packaged the Chrome version as the Firefox version. Fixed now!
