### ISSUE TITLE
Can't Donate

### ISSUE THREAD

**Issue by artworksmetal** [darktrojan/newtabtools#440]
I was going to send you a New Years present cause NTT makes my life much more pleasant, like the convenience of modern plumbing ( OK, that's a stretch).
Still, haven't donated in a while. Clicked on the Donate button, but it has the same behavior as the Backup  button.  Opens a Save As window.

FF 64.0.2 (64-bit)

**Comment by darktrojan** [comment]
You're right, I'd better fix that. I wonder how it happened…

**Comment by darktrojan** [comment]
[Apparently I've already fixed this once.](https://github.com/darktrojan/newtabtools/commit/58cfba673332f384ac128d58a72ac8b4fe42c198) That line keeps wandering off for some reason!

**Comment by darktrojan** [comment]
New version uploaded, and thank you!
