### ISSUE TITLE
Problem with Firefox Nightly 85.0a1

### ISSUE THREAD

**Issue by HilfsbereitDD** [darktrojan/newtabtools#473]
With the aktual Firefox Nightly i have a Problem with Showing Text by the Setup Icon. 
![grafik](https://user-images.githubusercontent.com/73550919/102021062-79498600-3d7d-11eb-968b-a12e50b08182.png)
In Firefox 83.0 (64-Bit) is ok, i can see only the Icon vor Setup.

**Comment by darktrojan** [comment]
I know what's causing that. I hadn't expected it to be a problem so soon, so you'll have to wait a while until I can fix it.

**Comment by HilfsbereitDD** [comment]
Hello darktrojan,

thanks for the quick Replay. Is ok, fix when have more Time. stay healthy ...

**Comment by DanaMW** [comment]
Fixed it for me:
menu#context-menu[type="context"] {
        display: none !important;
    }

**Comment by HilfsbereitDD** [comment]
how find this?

**Comment by DanaMW** [comment]
I already did. Somewhere in these old help topics i explained it once. And the above "fix" would be added to it. If you do not see that above as the fix you are way way WAY better off waiting for the man to fix it in the addon itself. My supposed fix is just a work around not authorized by the pretty people. Sorry.

**Comment by HilfsbereitDD** [comment]
is ok, i can wait ;-)

**Comment by WolfganP** [comment]
The same issue is present in 85.0beta2 as well.

**Comment by Lynx560** [comment]
and now the issue is present in 85.0 normal release (Jan 26, 2021)

Hope the fix comes soon... It is rather annoying...

**Comment by darktrojan** [comment]
You should try updating New Tab Tools to the version that fixed this over a month ago.

**Comment by Lynx560** [comment]
Just did .... Thank you
