### ISSUE TITLE
Unnecessary and too big description for settings 

### ISSUE THREAD

**Issue by mathewcoo** [darktrojan/newtabtools#477]
How can I remove the unnecessary and too big description for settings? She takes too much space.
The gear icon for the settings is enough. 
Thanks!
![Screenshot_1](https://user-images.githubusercontent.com/67975307/112972447-8fbef600-9150-11eb-97bf-352e43f88ce4.png)

**Comment by Skcamero** [comment]
I would like to second this - it's taking up nearly a third of my screen. I don't understand what the purpose of it is anyway since the gear icon is right there. All it does it take up screen space for no reason. I honestly thought it was a glitch rather than intentional.

**Comment by darktrojan** [comment]
That's actually the items from the context menu. Firefox doesn't support doing it in that way any more and just displays the items. You need to update New Tab Tools. This has been fixed for ages.
