### ISSUE TITLE
Latest Release appears to be corrupt on firefox addons site

### ISSUE THREAD

**Issue by TheArkive** [darktrojan/newtabtools#484]
Any chance of reverting or fixing the download on the Firefox Addon site?  The addon cannot be installed.  It says "You need an updated version of Firefox for this extension" despite me having the latest Firefox installed.  I'm still on v91 and Firefox won't do the update.

(I am using Firefox Portable - but have been doing so using this extension for years with no issues.)

I'm trying to extract the xpi of version 91 now to install it on another computer's Firefox installation.

On a separate but related note, if possible, having an archive of past releases would be nice too so we can manually roll back if necessary.

**Comment by darktrojan** [comment]
It's true that the latest version is marked as incompatible with the current version of Firefox. I did it deliberately, forgetting that the add-ons website isn't smart enough to pick a compatible version to show.

All of the old versions are here: https://addons.mozilla.org/en-US/firefox/addon/new-tab-tools/versions/

**Comment by darktrojan** [comment]
And now it's fixed.

**Comment by TheArkive** [comment]
Odd, I was having other issues at the time too (not related to newtabtools).  I couldn't manage my Mozilla Sync account.

Now all these seemingly unrelated things have now subsided.

Thanks for your quick response (and sorry for my belated one).
