### ISSUE TITLE
Link to another addon page

### ISSUE THREAD

**Issue by Speravir** [darktrojan/newtabtools#501]
Since Firefox 57 I had used a link from newtabtools to a page of another addon ([BookmarksHome](https://addons.mozilla.org/firefox/addon/bookmarkshome/)). This one I am using for even a longer time also in times before web extension API. This way I had advantages from both addons. Your addon I use on a daily basis (and still do), the second for other cases.

But now with Firefox 105 this stopped working. [I asked on forum camp-firefox.de for a possible solution](https://www.camp-firefox.de/forum/thema/135298-erweiterungs-seite-aus-anderer-erweiterung-heraus-aufrufen/) (in German). Sören Hentzschel, the administrator of this forum and himself addon developer, e.g. for the partly similar [New Tab Override](https://addons.mozilla.org/firefox/addon/new-tab-override/), answered:
* It is a consequence of fixing bug tickets: either [1711168 - support extensions in web_accessible_resources](https://bugzilla.mozilla.org/show_bug.cgi?id=1711168) or [1773115 - MV3 - specifying resource in "web_accessible_resources" prevents it's usage inside addon pages](https://bugzilla.mozilla.org/show_bug.cgi?id=1773115) in Fx 105 (or both).
* After conversation with a Firefox developer: Web developers have to adjust their addon – resources which are to be read by websites or other extensions must be declared in the `web_accessible_resources`.

The information about this necessary change was first forgotten to add to [Firefox 105 for developers](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/105) at MDN, but meanwhile it has subsequently been added.

It would be great if you could update your addon accordingly.

**Comment by darktrojan** [comment]
> After conversation with a Firefox developer: Web developers have to adjust their addon – resources which are to be read by websites or other extensions must be declared in the web_accessible_resources.

There's nothing in my add-on for other extensions to link to, but a link to another add-on would require _that add-on_ to mark stuff as accessible.
