### ISSUE TITLE
Apply grid spacing for spacing between recently closed tabs and grid

### ISSUE THREAD

**Issue by Eagle3386** [darktrojan/newtabtools#58]
Currently, there's no way to increase the spacing between the bar for recently closed tabs and the actual grid.

IMHO, from a design perspective it'd look pretty good if that spacing honors the grid spacing's value (small/medium/large) and position itself accordingly.
This way, one (e.g. me ;)) wouldn't click a page tile if the intension was to restore a tab.

**Comment by darktrojan** [comment]
It only took me a year :-)
