### ISSUE TITLE
Launcher: text is slightly cut at the bottom

### ISSUE THREAD

**Issue by XPJ38** [darktrojan/newtabtools#71]
French locale, running NTT35 and FF34.0 on Xubuntu 14.04.

Really minor issue.
When the launcher is enabled and placed at the bottom of the page, the "Restore previous session" text (or whatever it is called in English) is slightly cut:

![screenshot - 05012015 - 21 10 33](https://cloud.githubusercontent.com/assets/4924563/5619180/cd4f5854-951f-11e4-8898-517c514b7784.png)

On the contrary, the about:home page, which displays a similar launcher, doesn't have this issue:

![screenshot - 05012015 - 21-16-51](https://cloud.githubusercontent.com/assets/4924563/5619227/4860f17e-9520-11e4-8d6f-f43d85570e57.png)

I recall the launcher design was slightly different on previous versions and back then it didn't have this issue.

**Comment by darktrojan** [comment]
Hmm, there's a maximum width constraint on that button which is causing the text to wrap around. I've made a small change to the styling of the button and that's pushed it past the limit. Will fix, thanks.

**Comment by darktrojan** [comment]
Also FYI, "Téléchargements" doesn't fit when the launcher is on the sides. I don't see how that can be fixed though without making the whole launcher wider. You have such long words!

**Comment by XPJ38** [comment]
Thanks.

> Also FYI, "Téléchargements" doesn't fit when the launcher is on the sides.

Indeed, it doesn't when it's located on the right (although it looks just fine when it's on the left).
It would be great if the launcher width was automatically adjusted depending on the text. I tweaked content/newTab.css a bit and found out it looks much better with this piece of code (copy/paste it after .launchButton on line 259):

```css
:root[launcher="right"] #launcher .launchButton,
:root[launcher="left"] #launcher .launchButton {
  min-width: 0;
}
```
