### ISSUE TITLE
Custom CSS/JS option and Weave / Firefox Sync

### ISSUE THREAD

**Issue by gtgt** [darktrojan/newtabtools#73]
Hi!

I have two feature suggestion:

- Two textareas to settings wherewith advanced users can set their own css and javascript which will be included on newtab page. Custom js could also solve the "widgets" feature what an other user requested.
- Ability to sync settings with built-in weave / firefox sync, like we have in the flashblock addon for example. I know there is an export/import settings feature, but this could make settings synchronization much easier between browsers.

Thank you

**Comment by Eagle3386** [comment]
I suggest you use 2 tickets for two requests then. ;)
