### ISSUE TITLE
pin and close images incorrect on retina/hidpi devices

### ISSUE THREAD

**Issue by globau** [darktrojan/newtabtools#74]
the thumbnail pin and close images are incorrect on retina/hidpi devices.

![screenshot 2015-02-02 15 41 20](https://cloud.githubusercontent.com/assets/872825/5997139/f9c46a40-aaf1-11e4-9432-93ce16380f3d.png)

:hover
![screenshot 2015-02-02 15 41 26](https://cloud.githubusercontent.com/assets/872825/5997141/ff292f52-aaf1-11e4-944e-46826088b066.png)

**Comment by darktrojan** [comment]
Boom, fixed. On `unreleased`, anyway.
