### ISSUE TITLE
Tile's tooltip doesn't show renamed title

### ISSUE THREAD

**Issue by XPJ38** [darktrojan/newtabtools#78]
NTT 39.

Issue: after changing a tile's title, the tooltip of that tile shows the old title, not the new one.

Steps to reproduce:
* Get a tile that didn't have its title changed
* Edit its title to a new one
* Hover the tile and see that the tooltip still shows the old title, while the title underneath the thumbnail has been changed.

Screenshot:

![aaa](https://cloud.githubusercontent.com/assets/4924563/6471605/bdd8b718-c1ec-11e4-9f02-ce05179d3d75.png)

**Comment by dumbkid831** [comment]
Same problem, after restart firefox, modifications that i made changed back...

**Comment by XPJ38** [comment]
Can confirm it has been fixed in NTT 40. Thanks!
