### ISSUE TITLE
"Pin Tile and Remove Tile Buttons" works uncorrectly

### ISSUE THREAD

**Issue by skywinds5012** [darktrojan/newtabtools#84]
Version 41 in Simplified Chinese with FF37.0.2 under Win8.1x64. 
Only uncheck "Pin Tile and Remove Tile Buttons" could I kill the buttons on the tiles. Please take a look at it. 
Thank you for your work.

**Comment by yfdyh000** [comment]
#85 fixed this.

**Comment by darktrojan** [comment]
I'm a little confused about what you want here. Check the box if you want the buttons, uncheck it if you don't.

**Comment by skywinds5012** [comment]
Oh, I think you two should have a discussion about how this work. @yfdyh000 @darktrojan 
darktrojan, I think you mean that "check to show the buttons", but the Simplified Chinese translation here is "uncheck to show the buttons". There may have some misunderstanding about "Pin" and "Remove", a verb or a noun. 
看来你们俩需要讨论一下这个功能究竟是怎么实现的了。我看darktrojan的意思似乎是“去掉勾以去掉这两个按钮”，而yfdyh000你的翻译带来的意思是“打勾以去掉这两个按钮”，你们俩看来必须统一一下才行。

**Comment by yfdyh000** [comment]
@darktrojan The "Remove" word very like a verb, especially in Chinese (and perhaps also other languages).

Change the option text to `Show 'Pin Tile' and 'Remove Tile' Buttons` be able to clarify this point.

**Comment by darktrojan** [comment]
@yfdyh000 Okay, I've added quotes to the English. It should make more sense now. Do you want to change the Chinese before the next release?

**Comment by yfdyh000** [comment]
@darktrojan Done in #86. I think add the "Show" will more clearly, just an opinion.
