### ISSUE TITLE
Ability to set background colour

### ISSUE THREAD

**Issue by DoctorJellyface** [darktrojan/newtabtools#90]
Or gradient too maybe. Could be cool. I want this mainly because Web (Epiphany) has a slightly different colour on it's background, and I want Firefox to look as much as it as it can.

Thanks.

**Comment by darktrojan** [comment]
Why don't you make an image of the appropriate colour/gradient and set it as the background?

**Comment by DoctorJellyface** [comment]
Of course I can, but it's not as elegant.
