### ISSUE TITLE
Thumbnail not showig up for some sites

### ISSUE THREAD

**Issue by version365** [darktrojan/newtabtools#97]
Thumbnails are not showing up for some sites.. eg. imgur, gmail, google drive..
Other site's thumbnails work perfectly..
Edit : my ISP login page thumbnail also not showing..

**Comment by darktrojan** [comment]
That's actually because Firefox generates the thumbnails and it won't for certain types of page. It's a "privacy feature" but it'd be nice if you could turn it off.

**Comment by version365** [comment]
what "privacy feature" is this? and how to turn it off?

**Comment by darktrojan** [comment]
You can't turn it off, that was my point.

**Comment by ucolaf** [comment]
make manuel a screenshoot of you favorite site and save image. then select the image in the settings.
i do it for my favorite site, so i can see all after cache clear.
